import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {randomUUID} from 'node:crypto';
import {initialize} from './runtime.mjs';import {sha,encode} from '../../../pilots/atlas/tryfan/identity.mjs';
const {core}=await initialize(),fixtures=JSON.parse(fs.readFileSync(join(core.plan.stateRoot,'fixtures.json'),'utf8')),failures=[];
after(()=>{const p=join(core.plan.stateRoot,fs.existsSync(join(core.plan.stateRoot,'failure-matrix.json'))?'failure-matrix-repeat.json':'failure-matrix.json');fs.writeFileSync(p,encode(failures));});
const worker=(args)=>JSON.parse(execFileSync(process.execPath,['scripts/atlas/component-membership/worker.mjs',...args],{encoding:'utf8',timeout:30000}));
test('prospective hypotheses, source modules and evidence pins remain intact',()=>{assert.equal(core.plan.cases.length,9);assert.equal(Object.keys(core.plan.hypotheses).length,5);for(const [f,h] of Object.entries(core.plan.authoritativeHashes))assert.equal(sha(fs.readFileSync(f)),h);});
for(const f of fixtures.records)test('independent current/recent/oldest identities at '+f.depth,async()=>{
 for(const selection of ['current','recent','oldest']){const r=await core.measured(()=>core.resolveGeneration(f.store,f[selection],{hydrate:true}));assert.equal(r.measurement.reads.membership.calls,33);assert.equal(r.measurement.reads.components.calls,5);assert.equal(r.measurement.counters.ancestryTraversals,0);assert.equal(r.value.legacyGeneration,f.legacy);}
});
test('five immutable components shared over112 retained publications',()=>{const f=fixtures.records[2];assert.equal(f.footprint.components.files,5);assert.equal(new Set(f.history).size,112);assert.equal(f.footprint.publications.files,112);for(const id of [f.current,f.oldest])assert.deepEqual(core.resolveGeneration(f.store,id).publication.members,f.members);});
test('whole scientific generation reconstructs exactly',()=>{const f=fixtures.records[0],s=core.resolveGeneration(f.store,f.current,{hydrate:true});assert.equal(sha(encode(s.value)),f.legacy);assert.equal(s.value.catalogue.artifacts.length,310);assert.equal(s.value.understanding.results.length,6);assert.equal(s.value.knowledge.contract,'atlas-semantic-evidence/v1');});
test('location binding changes do not redefine source/product identity',()=>{const f=fixtures.records[0],s=core.resolveGeneration(f.store,f.current,{hydrate:true}),dir=join(core.plan.stateRoot,'locator-'+randomUUID());fs.mkdirSync(dir);const other={...s.locators,test:'unpublished-test-locator'};const id=core.prepare(dir,s.value,other,{ordinal:1});const p=core.resolveGeneration(dir,id,{published:false}).publication;assert.equal(p.members.catalogue,f.members.catalogue);assert.equal(p.legacyGeneration,f.legacy);assert.notEqual(p.members.locators,f.members.locators);assert.throws(()=>core.resolveGeneration(dir,id),e=>e.code==='store-absent');});
for(const [scenario,expected] of [['unpublished-complete-orphan','generation-unpublished'],['unknown-generation','generation-unpublished'],['corrupt-selected-component','metadata-integrity'],['missing-selected-component','component-unavailable'],['corrupt-membership-node','metadata-integrity'],['between-request-mutation','metadata-integrity'],['corrupt-unselected-history-detected-by-historical-read','metadata-integrity']])test('explicit failure '+scenario,()=>{const dir=join(core.plan.stateRoot,'failure-'+scenario+'-'+randomUUID());fs.cpSync(fixtures.records[0].store,dir,{recursive:true});const r=JSON.parse(execFileSync(process.execPath,['scripts/atlas/component-membership/failure-worker.mjs',dir,scenario],{encoding:'utf8',timeout:30000}));assert.equal(r.code,expected);assert.ok(r.rootUnchanged);failures.push(r);});
for(const q of ['Q05','Q21','Q18'])test('fresh serving qualification equals e88b575 '+q,()=>{const f=fixtures.records[2],r=worker([f.store,f.oldest,q,'2']),old=JSON.parse(fs.readFileSync('docs/research/atlas-generation-scaling-results.json','utf8'));assert.equal(r.samples[0].qualifiedSha256,old.rows.find(x=>x.query===q).qualifiedSha256);assert.deepEqual(r.samples[0].reads,r.samples[1].reads);assert.equal(r.samples[1].reads.membership.calls,33);assert.equal(r.samples[1].reads.components.calls,5);});
test('real retained lifecycle, two interruptions and existing isolated HTTP consumers',()=>{const output=JSON.parse(execFileSync(process.execPath,['scripts/atlas/component-membership/lifecycle-worker.mjs'],{encoding:'utf8',timeout:180000}));assert.equal(output.failures,2);assert.equal(output.recomputed,2);assert.equal(output.reused,2);assert.equal(output.exactReplays,10);const first=JSON.parse(fs.readFileSync(join(core.plan.stateRoot,'lifecycle.json'),'utf8')),again=JSON.parse(fs.readFileSync(join(core.plan.stateRoot,'lifecycle-repeat.json'),'utf8'));assert.equal(first.g1,again.g1);assert.equal(first.g2,again.g2);assert.ok(again.exactAcceptedU1);});
test('all27 measurement cells preserve structural bounds',()=>{const v=JSON.parse(fs.readFileSync('docs/research/atlas-component-membership-results.json','utf8'));assert.equal(v.rows.length,27);for(const r of v.rows){assert.equal(r.reads.membership.calls,33);assert.equal(r.counters.ancestryTraversals,0);assert.equal(r.reads.publications.calls,1);if(r.mode!=='membership')assert.equal(r.reads.components.calls,5);}});

test('incomplete required locator closure cannot publish or poison current',()=>{const f=fixtures.records[0],dir=join(core.plan.stateRoot,'incomplete-'+randomUUID());fs.cpSync(f.store,dir,{recursive:true});const previous=fs.readFileSync(join(dir,'current.json')),snapshot=core.resolveGeneration(dir,f.current,{hydrate:true}),candidate=core.prepare(dir,snapshot.value,{},{ordinal:8,predecessor:f.current});assert.throws(()=>core.publish(dir,candidate));assert.deepEqual(fs.readFileSync(join(dir,'current.json')),previous);assert.throws(()=>core.resolveGeneration(dir,candidate),e=>e.code==='generation-unpublished');assert.equal(core.load(dir,{verify:true}).verification.artifacts,310);});
