// S6 measurement/acceptance driver. Frozen S1-S5 modules are read-only.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync,statSync} from 'node:fs';import {join,resolve} from 'node:path';import {fork,spawnSync,execFileSync} from 'node:child_process';import {performance} from 'node:perf_hooks';import {cpus,totalmem} from 'node:os';
import {STORE,load} from './generations.mjs';import {ROOT,DATA} from './catalogue.mjs';import {encode,sha} from './identity.mjs';import {methods} from './derivations.mjs';import {prepareMixedBaseline,forkBaseline} from './updates.mjs';import {exercise} from './tests/publication-harness.mjs';
const baseline=JSON.parse(readFileSync(join(ROOT,'docs/research/tryfan-pilot-s6-baseline.json'),'utf8')),plan=JSON.parse(readFileSync(join(ROOT,'docs/research/tryfan-regional-pilot-plan.json'),'utf8')),output=join(ROOT,'docs/research/tryfan-pilot-s6-results.json'),runtime=join(STORE,'s6-acceptance'),start=performance.now();
for(const [p,h] of Object.entries(baseline.systemSha256))assert.equal(sha(readFileSync(join(ROOT,p))),h,'Frozen system '+p);
const canonical=load(STORE);assert.equal(canonical.generation,baseline.current);const checks=[];const check=(id,name,ok,detail)=>{checks.push({id,name,status:ok?'PASS':'FAIL',detail});};
function run(file,args=[]){const t=performance.now(),p=spawnSync(process.execPath,[join(import.meta.dirname,file),...args],{encoding:'utf8',timeout:60000,maxBuffer:6e6});assert.equal(p.status,0,p.stderr);return {milliseconds:performance.now()-t,value:JSON.parse(p.stdout)};}
const stats=s=>{const v=s.map(x=>typeof x==='number'?x:x.milliseconds).sort((a,b)=>a-b);return {samples:s,median:v[Math.floor(v.length/2)],p95:v[Math.min(v.length-1,Math.ceil(.95*v.length)-1)],min:v[0],max:v.at(-1)};};
async function service(store=STORE){const t=performance.now(),p=fork(join(import.meta.dirname,'tests/service-process.mjs'),[JSON.stringify({store})],{silent:true});let stderr='';p.stderr.on('data',s=>stderr+=s);const next=()=>new Promise((r,j)=>{const timer=setTimeout(()=>{p.kill();j(Error('Service timeout '+stderr));},30000);p.once('message',v=>{clearTimeout(timer);r(v);});p.once('error',j);});const ready=await next();return {...ready,p,processStartupMilliseconds:performance.now()-t,stop:async()=>{const n=next();p.send('stop');return n;}};}
function footprint(dir){let files=0,bytes=0;for(const e of readdirSync(dir,{withFileTypes:true})){if(e.isDirectory()){const r=footprint(join(dir,e.name));files+=r.files;bytes+=r.bytes;}else{files++;bytes+=statSync(join(dir,e.name)).size;}}return {files,bytes};}
const independent=[];if(!process.argv.includes('--check')){
 assert.ok(!existsSync(runtime),'Fresh evaluation requires absent isolated acceptance root');mkdirSync(runtime,{recursive:true});
 for(let i=0;i<2;i++)independent.push(run('rebuild-s6.mjs',[join(runtime,'rebuild'+i)]));
}else{for(let i=0;i<2;i++)independent.push({value:JSON.parse(readFileSync(join(runtime,'rebuild'+i+'.json'),'utf8'))});}
for(let i=0;i<2;i++)writeFileSync(join(runtime,'rebuild'+i+'.json'),encode(independent[i].value));
const empty=independent.map(x=>load(x.value.store,{generation:x.value.generation}));check('A','Independent empty builds',empty[0].generation===empty[1].generation && ['catalogue','knowledge','serving'].every(k=>encode(empty[0].value[k])===encode(load(STORE,{generation:baseline.history[1].generation}).value[k])),{generations:empty.map(s=>s.generation),sameSequence:true,canonicalDifferentParentHistory:true});
let U1,U2;if(process.argv.includes('--check')){const old=JSON.parse(readFileSync(output,'utf8'));U1=old.updates.U1;U2=old.updates.U2;}else{
 U1=await exercise(empty[0].value?independent[0].value.store:null,'U1');const mixed=join(runtime,'mixed');forkBaseline(mixed,{source:independent[1].value.store});prepareMixedBaseline({store:mixed});U2=await exercise(mixed,'U2');}
for(const [key,v] of Object.entries({U1,U2})){check(key==='U1'?'H':'J',key+' actual mixed update',v.logical.recomputed.length===2&&v.logical.reused.length===2,{from:v.logical.from,to:v.logical.to,recomputed:v.logical.recomputed,reused:v.logical.reused});}
check('K','Abrupt process exits with fresh recovery', [U1,U2].every(v=>v.failures.length===4&&v.failures.every(f=>f.exitCode===91&&f.current===v.logical.from&&f.freshService===v.logical.from)),{failures:8,checkpoints:['F1','E1','F2','F3']});
const updated=load(independent[0].value.store);check('G','Independent scalar records equal final retained pilot',encode(updated.value.understanding)===encode(canonical.value.understanding),{results:6,active:4,method:canonical.value.understanding.basis.methodRevision});
const m=await methods();let replay,freshness;try{const t=performance.now();replay=m.replay(updated.value.understanding,updated.value.catalogue,updated.locators);replay.milliseconds=performance.now()-t;const samples=[];for(let i=0;i<20;i++){const t=performance.now();const a=m.assess(updated.value.understanding,updated.value.catalogue,updated.locators);samples.push({milliseconds:performance.now()-t,statuses:a.map(x=>x.assessment.status)});}freshness=stats(samples);}finally{await m.close();}
check('I','Replay six from retained pixels',replay.checks.length===6&&replay.checks.every(r=>r.exact),replay.checks);
const fresh=[];for(let i=0;i<5;i++){const s=await service();try{const c=run('client/http-consumer.mjs',[s.url]);const recovery=run('cli.mjs',['validate']);fresh.push({serviceStartupMilliseconds:s.startup,processStartupMilliseconds:s.processStartupMilliseconds,consumerMilliseconds:c.milliseconds,loadMilliseconds:recovery.value.metrics.loadMilliseconds,recoveryMilliseconds:recovery.milliseconds,answerSha256:sha(encode(c.value.answer)),bytes:Buffer.byteLength(encode(c.value)),generation:c.value.generation});}finally{await s.stop();}}
check('N','Five fresh HTTP/consumer processes',fresh.every(f=>f.generation===baseline.current&&f.answerSha256===fresh[0].answerSha256),fresh.map(f=>f.answerSha256));
const s=await service();let workload,answers={},assets=[],history,serviceMetrics,pythonMemory;
try{const root=s.url+'/pilot/v1/g/'+s.generation,point=plan.scope.probes[0].centre;
 async function timed(path,request){const t=performance.now(),r=await fetch(root+path,request?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)}:{}),b=Buffer.from(await r.arrayBuffer());return {milliseconds:performance.now()-t,status:r.status,bytes:b.length,sha256:sha(b),value:r.headers.get('content-type')?.includes('json')?JSON.parse(b):null};}
 const properties=['worldcover-native','nrw-native','derived-slope','derived-area-ratio','place-evidence'];const warm={};for(const p of properties)warm[p]=[];
 // Twenty batches of the same prospective five representative questions; full frozen matrix separately below.
 for(let i=0;i<20;i++)for(const property of properties){const r=await timed('/query',{property,place:{crs:'EPSG:27700',point}});assert.equal(r.status,200);answers[property]=r.value;warm[property].push({milliseconds:r.milliseconds,bytes:r.bytes,sha256:r.sha256});}
 const native=JSON.parse(readFileSync(join(import.meta.dirname,'query-matrix.json'),'utf8')),matrix=[];
 for(const q of native.queries.filter(q=>q.id!=='Q17')){const p=native.probes[q.probe],place=q.property==='worldcover-support'?{crs:'EPSG:27700',bounds:[p[0]-200,p[1]-200,p[0]+200,p[1]+200]}:{crs:'EPSG:27700',point:p};const r=await timed('/query',{property:q.property,place,time:q.time});matrix.push({id:q.id,status:r.status,sha256:r.sha256,answer:r.value});}
 const manifest=(await timed('/manifest')).value;for(const a of manifest.assets){const r=await timed(a.url.slice(root.length-s.url.length));assert.equal(r.sha256,a.sha256);assets.push({family:a.family,bytes:r.bytes,sha256:r.sha256,milliseconds:r.milliseconds});}
 const tile=manifest.terrain.find(t=>t.family==='terrain-regional'&&t.tile.z===14);const tr=await timed(tile.url.slice(root.length-s.url.length));const missing=await timed('/terrain/terrain-common/13/4005/2664.png');check('C','Exact tile and missing support',tr.sha256===tile.sha256&&missing.status===503,{tile,bytes:tr.bytes,milliseconds:tr.milliseconds,missing:missing.status});
 check('B','Single generation Q21',answers['place-evidence'].answers.length===6&&answers['place-evidence'].answers.every(a=>a.response.generation===baseline.current),{sha256:sha(encode(answers['place-evidence']))});
 const wc=answers['worldcover-native'].answers[0].records[0],nrw=answers['nrw-native'].answers[0].records[0];check('D','Native raster and frozen support queries',wc.cell.code===30&&manifest.layers.worldcover.grid.cells===185036&&matrix.filter(q=>['Q07','Q19','Q20'].includes(q.id)).every(q=>q.answer.answers[0].records[0].assignments.cells>0),{code:wc.cell.code,grid:manifest.layers.worldcover.grid,matrixHashes:matrix.map(q=>({id:q.id,sha256:q.sha256}))});
 check('E','Native vector identity and survey time',nrw.feature.id==='486832'&&nrw.claim.native.fields.phase1_code==='D.1.1'&&manifest.layers.nrw.featureCount===193,{feature:nrw.feature,time:nrw.context.time});
 const co=await timed('/query',{property:'coexisting-semantic',place:{crs:'EPSG:27700',point}});check('F','Coexisting native evidence',co.value.answers[0].records.length===2&&!co.value.answers[0].value,{time:co.value.answers[0].records.map(r=>r.context.time),mapping:wc.claim.interpretation});
 const provenance=await timed(answers['derived-slope'].provenanceURL.slice(root.length-s.url.length));check('L','Generation provenance and rights',provenance.value.sources.length===5&&provenance.value.derived.length===6&&manifest.families.every(f=>f.rightsURL),{bytes:provenance.bytes,sha256:provenance.sha256,milliseconds:provenance.milliseconds});
 check('M','Unsupported and current queries reject fallback',matrix.filter(q=>['Q13','Q14','Q16'].includes(q.id)).every(q=>['unsupported','outside-support'].includes(q.answer.result?.reason)),{fixtureEvidence:'S2 query/native tests and S4 HTTP H15 independently rerun; no real zero/non-detection invented'});
 const historyStart=performance.now();const historical=await fetch(s.url+'/pilot/v1/g/'+baseline.history[1].generation+'/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({property:'place-evidence',place:{crs:'EPSG:27700',point}})});const ht=performance.now(),hv=await historical.json();history={generation:hv.generation,sha256:sha(encode(hv)),bodyReadMilliseconds:performance.now()-ht,requestMilliseconds:performance.now()-historyStart,slope:hv.answers.find(a=>a.property==='derived-slope').response.answers[0].result.claim.result.value.value};assert.equal(history.slope,11.837956999552308);
 const loads=[];for(const readers of [1,4]){const samples=[];let counter=0;const t=performance.now();await Promise.all(Array.from({length:readers},async()=>{while(counter<100){const i=counter++;const r=await timed('/query',{property:i%2?'nrw-native':'worldcover-native',place:{crs:'EPSG:27700',point}});samples.push({milliseconds:r.milliseconds,status:r.status,bytes:r.bytes});}}));loads.push({readers,requests:100,elapsedMilliseconds:performance.now()-t,...stats(samples),errors:samples.filter(x=>x.status!==200).length});}
 // Targeted direct worker measurement, never private files or unrelated process data.
 try{pythonMemory=JSON.parse(execFileSync('powershell',['-NoProfile','-Command',`function WorkerTree($parentPid) { Get-CimInstance Win32_Process -Filter "ParentProcessId = $parentPid" | ForEach-Object { if ($_.Name -like 'python*') { $worker = Get-Process -Id $_.ProcessId; [pscustomobject]@{pid=$_.ProcessId;name=$_.Name;workingSetBytes=$worker.WorkingSet64}; WorkerTree $_.ProcessId } } }; @(WorkerTree ${s.p.pid}) | ConvertTo-Json -Compress`],{encoding:'utf8'}));}catch(e){pythonMemory={unavailable:e.message};}

 workload={warm:Object.fromEntries(Object.entries(warm).map(([p,s])=>[p,stats(s)])),controlledLoad:loads,nativeMatrix:matrix.map(q=>({id:q.id,status:q.status,sha256:q.sha256})),provenance:{bytes:provenance.bytes,milliseconds:provenance.milliseconds}};
}finally{serviceMetrics=await s.stop();}
check('P','Pinned readers through real publication', [U1,U2].every(v=>v.racing.every(r=>r.pinned===v.logical.from)&&v.racing.at(-1).generation===v.logical.to),{browserEvidence:'S4 matched full-core/400m; S5 U2 actual scene refresh rerun by regression suite',races:[U1.racing,U2.racing]});
check('O','Retained bytes and canonical state immutable',load(STORE).generation===baseline.current&&encode(load(STORE).value)===encode(canonical.value),canonical.verification);
const footprintClasses=Object.fromEntries(['generations','locators','artifacts','staging'].map(c=>[c,footprint(join(STORE,c))]));const logical={baselineSha256:sha(readFileSync(join(ROOT,'docs/research/tryfan-pilot-s6-baseline.json'))),emptyGeneration:empty[0].generation,updated:updated.generation,understandingSha256:sha(encode(updated.value.understanding)),canonical:baseline.current,freshAnswerSha256:fresh[0].answerSha256,queryHashes:workload.nativeMatrix,sourceVerification:canonical.verification};
const record={schema:'atlas-tryfan-s6-measured-exit/v1',checks,logical,logicalSha256:sha(encode(logical)),independentBuilds:independent.map(x=>({generation:x.value.generation,milliseconds:x.milliseconds??null})),updates:{U1,U2},fresh,workload,replay,freshness,assets,history,service:serviceMetrics,pythonMemory,storage:footprintClasses,acceptanceStorage:footprint(runtime),endToEndMilliseconds:performance.now()-start,runtime:{node:process.version,platform:process.platform,cpu:cpus()[0].model,cores:cpus().length,totalMemoryBytes:totalmem(),cache:'Warm OS caches;no query/byte cache. Native initialized array/bbox reused. Private ETag responses verify bytes even for304.',memory:'Node RSS and direct Python worker working set separately; no aggregate or peak-RSS claim'},limitations:baseline.limitations};
if(process.argv.includes('--check')){const old=JSON.parse(readFileSync(output,'utf8'));assert.equal(old.logicalSha256,record.logicalSha256);const initial=join(runtime,'reproduction.json');writeFileSync(existsSync(initial)?join(runtime,'reproduction-repeat.json'):initial,encode(record));console.log(encode({deterministic:true,logicalSha256:record.logicalSha256,pythonMemory:record.pythonMemory}));}
else {writeFileSync(output,encode(record));console.log(encode({checks:checks.map(c=>[c.id,c.status]),logicalSha256:record.logicalSha256,endToEndMilliseconds:record.endToEndMilliseconds}));}
