// Read-only accountable evidence adapter; no data acquisition or preparation writes.
import fs from 'node:fs';
import {join} from 'node:path';
import * as E from '../exe-water-query-proof/runtime.mjs';
import {DATA,ROOT} from '../../../pilots/atlas/tryfan/catalogue.mjs';
import {encode,sha,requireThat} from '../../../pilots/atlas/tryfan/identity.mjs';
export const H=import.meta.dirname,plan=JSON.parse(fs.readFileSync(join(H,'plan.json'),'utf8'));
export const digest=x=>sha(encode(x)),clone=structuredClone;
export const unknown=reason=>({kind:'unknown',reason});
export const epoch=(value,precision,basis)=>({kind:'epoch',value,precision,basis});
export const need=(ok,message)=>requireThat(ok,'temporal-proof-invalid',message);
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const prior=read(join(ROOT,'docs/research/atlas-regional-dependencies-results.json'));
export function originalBase(){const values={};for(const [k,id]of Object.entries(prior.members[0])){const body=fs.readFileSync(join(prior.store,'components',id+'.json'),'utf8');need(sha(body)===id,'Original regional component unavailable/corrupt');values[k]=JSON.parse(body).value;}const pbody=fs.readFileSync(join(prior.store,'publications',prior.history[0]+'.json'),'utf8');need(sha(pbody)===prior.history[0],'Original regional publication changed');const {locators,...parts}=values;return {value:{...JSON.parse(pbody).header,...parts},locators,priorStore:prior.store};}
let cached;
export async function loadEvidence(){if(cached)return cached;const began=performance.now(),raw=E.reader(),c=await E.contract(),native=E.build(raw,c.fixtures);E.check(native,c.validate);const base=originalBase(),anchors={};
 const add=(id,region,physical,sourceTime,retention,preparation,support,qualification,lineage,feature=null,nativeRecord=null)=>{anchors[id]={assignment:id,region,feature,physical,sourceTime,retention,preparation,support,qualification,lineage,nativeRecord,observationIdentity:{kind:'source-qualified-assignment',id,limitation:'Explicit source/product/selector/support; not inferred physical observation identity from co-location'}};};
 const rr=base.value.riffelhornRegistration;
 for(const identity of plan.selected.riffelhorn){const row=rr.records.find(v=>v.identity===identity);need(row,'Missing selected prepared record');const e=row.temporal['evidence-epoch'],s=row.temporal['product-reference'];const physical=e.status==='known'?{role:e.role,extent:epoch(String(e.year),'year',e.basis)}:{role:'observation',extent:unknown(e.reason)};
  const sourceTime=s.status==='known'&&s.basis==='native year_rel release'?epoch(String(s.year),'year',s.basis+'; exact release instant unknown'):unknown('Product/reference edition is not established source recording/publication time; original product-reference remains in lineage');
  add('riffelhorn:'+identity,'riffelhorn',physical,sourceTime,unknown('Selected per-input acquisition date not recovered here; exact retained input receipts remain linked'),unknown('Preparation identity known; calendar run time not a source observation'),{geometry:{kind:'asset',asset:{href:'public-data-relative:derived/atlas/riffelhorn/riffelhorn-qualified-fixture-v1/'+rr.preparationRevision+'/'+row.preparedAsset,selector:identity},crs:{status:'known',value:{name:row.nativeCrs,identifier:row.nativeCrs}},interpretation:'Full native support; regional core applicability remains separate'},meaning:'Prepared evidence/support metadata, not a fabricated value at a point',grain:{status:'unknown',reason:'Source-specific grain; see unchanged preparation'}},{nativeMeaning:rr.qualification[row.family.startsWith('geocover')?'geocover':row.family==='glaciers'||row.family==='debris'?'glamos':row.family],rights:rr.rightsBoundary,limitations:'Native meaning/time and source input records retained; no seamless datum fusion or current state'},{preparedRevision:rr.preparationRevision,preparedArtifact:rr.preparedArtifacts.find(a=>a.path===row.preparedAsset),product:row.product,inputManifest:rr.inputs,record:row},identity,row);
 }
 const app=base.value.catalogue.families.find(f=>f.id==='appearance');
 add('tryfan:appearance','tryfan',{role:'observation',extent:{kind:'instant',value:app.nativeMetadata.observation.acquisition_time_utc,precision:'second',basis:'Retained official acquisition timestamp including recorded milliseconds; metadata only'}},unknown('Exact source recording/publication time not established; product ID timestamp not parsed as publication'),unknown('Exact retained acquisition receipt remains linked, not inferred from mtime'),unknown('Prepared artifact identity, transformation known; no added preparation clock'),{geometry:{kind:'native-rectangle',crs:{name:'EPSG:27700',identifier:'EPSG:27700'},bounds:app.nativeMetadata.aoi.bounds,axisOrder:'xy'},meaning:'Dated observed/prepared appearance metadata; not calibrated material properties',grain:{status:'known',value:'Native10m / prepared10m; not accuracy'}},{rights:app.nativeMetadata.rights,limitations:app.nativeMetadata.semantics,manual:app.nativeMetadata.visualAcceptance},{source:app.source,product:app.product,representations:app.representations,nativeMetadata:app.nativeMetadata});
 const ctx=base.value.tryfanDependencyState,st=base.value.tryfanDerived,first=st.results[st.active['tryfan-summit|slope']];
 add('tryfan:terrain','tryfan',{role:'observation',extent:unknown('Exact accepted represented-heightfield observation epoch unknown')},unknown('National release/publication unestablished'),unknown('Retained source receipt does not establish physical date'),unknown('Exact preparation identity elsewhere; no invented time'),{geometry:{kind:'native-point',crs:{name:'EPSG:27700',identifier:'EPSG:27700'},coordinates:first.support.point},meaning:first.support.meaning,grain:{status:'known',value:first.parameters.sampling}},{rights:first.qualification.sources[0].rights,limitations:first.qualification},{sources:ctx.sources,acceptedResult:first.revision});
 for(const [key,colId,claimId]of [['exe:wfd','collection:wfd','claim:wfd:GB510804505600:0'],['exe:rfo','collection:rfo','claim:rfo:31383:0']]){const col=native.bundle.collections.find(c=>c.id===colId),claim=col.claims.find(q=>q.id===claimId);need(claim,'Missing selected source-native event/reference');const context={...col.context,...claim.context},file=raw.sources[colId.endsWith('wfd')?'wfd.geojson':'rfo.geojson'];const resource=native.bundle.resources.find(a=>a.ref.id===col.product.id&&a.ref.kind==='product');
  const physical=key.endsWith('wfd')?{role:'observation',extent:unknown('Classification2019/reference boundary is not physical observation time')}:context.time[0];
  add(key,'exe',physical,key.endsWith('wfd')?epoch('2025-06-23','day','Retained WFD catalogue publication'):unknown('RFO catalogue revision is not the source-record publication time of this event'),{kind:'instant',value:file.retrievedUtc,precision:'second',basis:'Actual retained source acquisition receipt'},unknown('No new geographic preparation'),context.support,{rights:resource.rights,nativeContext:context,limitations:col.context.evidence.limitations},{source:file,product:col.product,nativeClaim:claim},key.endsWith('wfd')?'wfd:GB510804505600':'rfo:31383',claim);
 }
 for(const month of ['2024-03','2024-09'])for(const kind of ['point','support']){const q=E.MATRIX.queries.find(q=>q.id==='P1-'+kind+'-'+month),answer=E.resolveQuery(native,raw,q),col=native.bundle.collections.find(c=>c.id==='collection:'+month),file=raw.sources['monthly-'+month+'.tif'],resource=native.bundle.resources.find(a=>a.ref.id===col.product.id&&a.ref.kind==='product');
  add('exe:'+month+':'+kind,'exe',col.context.time[0],unknown('Parent last_modified is storage metadata, not proven provider publication'),{kind:'instant',value:file.subset.retrievedUtc,precision:'second',basis:'Actual retained native-window acquisition receipt; subsecond source precision retained'},unknown('Lossless native-window reencoding documented; completion time not separately established'),answer.claim?.context.support??{geometry:{kind:'native-rectangle',crs:{name:'EPSG:27700',identifier:'EPSG:27700'},bounds:q.bounds,axisOrder:'xy'},meaning:'Selected native cell centres, not fractional cover or homogeneous observation',grain:col.context.support.grain},{rights:resource.rights,nativeContext:col.context,limitations:col.context.evidence.limitations},{source:file,product:col.product,method:native.method,query:q},null,answer);
 }
 cached={base,anchors,raw,native,validateSemantic:c.validate,setup:{milliseconds:performance.now()-began,verifiedExeFiles:Object.keys(raw.sources).length,verifiedExeBytes:Object.values(raw.sources).reduce((n,v)=>n+v.bytes,0),retainedDirectoryFiles:Object.keys(raw.directorySha256).length,records:Object.keys(anchors).length,RSS:process.memoryUsage().rss}};return cached;}
export function fullNativeSummary(e,slot){const q=slot==='pair'?E.MATRIX.queries.find(q=>q.id==='P1-compare'):E.MATRIX.queries.find(q=>q.id==='P1-support-'+slot);need(q,'Missing accepted native summary query');return E.resolveQuery(e.native,e.raw,q);}
export function verifyExe(){const t=performance.now(),raw=E.reader();return {raw,milliseconds:performance.now()-t,files:Object.keys(raw.sources).length,bytes:Object.values(raw.sources).reduce((n,s)=>n+s.bytes,0)};}
