// Isolated temporal components over unchanged retained multi-region/dependency core.
import fs from 'node:fs';import {join,relative,resolve} from 'node:path';
import * as D from '../regional-dependencies/integration.mjs';
import * as T from './model.mjs';import * as E from './evidence.mjs';
import {encode,sha} from '../../../pilots/atlas/tryfan/identity.mjs';
export {T,E,D};export const C=D.C,M=D.M;
export const kinds=[...D.I.plan.components,...D.extras,'temporalKnowledge','temporalDerived'];
let ready,evidence,G;
export async function initialize(){if(ready)return ready;ready=(async()=>{await D.initialize();evidence=await E.loadEvidence();G=await import('../../../pilots/atlas/tryfan/generations.mjs');fs.mkdirSync(T.plan.stateRoot,{recursive:true});M.plan.stateRoot=T.plan.stateRoot;D.I.plan.stateRoot=T.plan.stateRoot;C.plan.stateRoot=T.plan.stateRoot;C.kinds.splice(0,C.kinds.length,...kinds);C.configure({canonicalGeneration});return evidence;})();return ready;}
function nativeOf(v){const base={...v};for(const k of [...D.extras,'temporalKnowledge','temporalDerived','tryfanRegistration','riffelhornRegistration'])delete base[k];return base;}
function canonicalGeneration(v){
 E.need(sha(encode(G.canonicalGeneration(nativeOf(v))))===D.I.plan.regions.tryfan.acceptedGeneration,'Accepted Tryfan native scientific state changed');
 for(const k of ['tryfanRegistration','riffelhornRegistration'])E.need(encode(v[k])===encode(evidence.base.value[k]),'Native regional registration identity changed');
 T.validateLedger(v.temporalKnowledge,evidence);T.validateDerived(v.temporalKnowledge,v.temporalDerived,evidence);
 const issues=evidence.validateSemantic(T.bundle(v.temporalKnowledge));E.need(issues.length===0,'Frozen semantic validation: '+issues.join(';'));
 for(const region of ['tryfan','riffelhorn']){const ctx=v[region+'DependencyState'],st=v[region+'Derived'],base=evidence.base.value[region+'DependencyState'];const expected=region==='riffelhorn'&&v.temporalKnowledge.ordinal>=2?M.change(base,T.plan.correction.riffelhorn):base;
  E.need(encode(ctx)===encode(expected),'Cross-region leakage or incompatible temporal/dependency context');M.validate(ctx,st);M.validateSemantic(ctx,st);for(const [id,r]of Object.entries(evidence.base.value[region+'Derived'].results))E.need(encode(st.results[id])===encode(r),'Historical regional derivation lost');
  C.count('regionalActiveChecks',Object.keys(st.active).length);C.count('regionalRetainedChecks',Object.keys(st.results).length);
 }
 C.count('temporalRevisionChecks',v.temporalKnowledge.records.length);C.count('temporalSemanticClaims',T.visible(v.temporalKnowledge).length);return v;
}
export function owned(store){const p=resolve(store),r=relative(resolve(T.plan.stateRoot),p);E.need(r&&!r.startsWith('..'),'Explicit isolated temporal child required');return C.owned(store);}
export async function seed(store){await initialize();fs.mkdirSync(store,{recursive:true});owned(store);fs.mkdirSync(join(store,'artifacts'),{recursive:true});for(const f of fs.readdirSync(join(evidence.base.priorStore,'artifacts'))){const bytes=fs.readFileSync(join(evidence.base.priorStore,'artifacts',f));const out=join(store,'artifacts',f);fs.writeFileSync(out,bytes,{flag:'wx'});}const value=E.clone(evidence.base.value);value.temporalKnowledge=T.transition(null,evidence,0);value.temporalDerived=T.emptyDerived();return {value,locators:E.clone(evidence.base.locators),setup:evidence.setup};}
export async function revise(value,stage){await initialize();const next=E.clone(value),t=performance.now();next.temporalKnowledge=T.transition(value.temporalKnowledge,evidence,stage);const incremental=T.recompute(next.temporalKnowledge,value.temporalDerived,evidence),full=T.recompute(next.temporalKnowledge,T.emptyDerived(),evidence,{full:true});E.need(encode(T.currentDerived(incremental.state))===encode(T.currentDerived(full.state)),'Full/scoped temporal receipts differ');next.temporalDerived=incremental.state;let regional={recomputed:0,expected:[],reuse:184};
 if(stage===2){const before=value.riffelhornDependencyState,after=M.change(before,T.plan.correction.riffelhorn),expected=M.expectedAffected(before,after,value.riffelhornDerived);const scoped=await M.recompute(after,value.riffelhornDerived),clean=await M.recompute(after,M.empty('riffelhorn'),{full:true});E.need(encode(M.currentContent(scoped.state))===encode(M.currentContent(clean.state)),'Regional full/scoped mismatch');E.need(expected.length===8&&scoped.measurement.recomputed===8,'Incorrect scoped correction closure');next.riffelhornDependencyState=after;next.riffelhornDerived=scoped.state;regional={recomputed:8,expected,reuse:176,scoped:scoped.measurement,full:clean.measurement};}
 return {value:next,measurement:{milliseconds:performance.now()-t,stage,temporal:incremental.measurement,temporalFull:full.measurement,regional,RSS:process.memoryUsage().rss}};}
export function prepare(store,value,locators,options){owned(store);E.need(options.ordinal===value.temporalKnowledge.ordinal+1,'Publication/knowledge mismatch');return C.prepare(store,value,locators,options);}
export const resolveGeneration=(store,id,options)=>C.resolveGeneration(owned(store),id,options);
export const current=store=>C.root(owned(store));export const recover=store=>C.recover(owned(store));export const measured=C.measured;
export async function publish(store,id,options={}){await initialize();const start=performance.now(),snap=resolveGeneration(store,id,{hydrate:true,published:false}),v=snap.value;E.need(snap.publication.ordinal===v.temporalKnowledge.ordinal+1,'Publication/knowledge mismatch');const previous=fs.existsSync(join(store,'current.json'))?resolveGeneration(store,current(store).generation,{hydrate:true}):null;
 E.need(v.temporalKnowledge.ordinal===(previous?.value.temporalKnowledge.ordinal??-1)+1,'Knowledge revision order/current mismatch');if(previous)E.need(encode(v.temporalKnowledge.records.slice(0,previous.value.temporalKnowledge.records.length))===encode(previous.value.temporalKnowledge.records),'Immutable knowledge history rewritten');
 const numericalReplay=[];for(const region of ['tryfan','riffelhorn']){const full=await M.recompute(v[region+'DependencyState'],M.empty(region),{full:true});E.need(encode(M.currentContent(full.state))===encode(M.currentContent(v[region+'Derived'])),'Full regional replay mismatch');numericalReplay.push(full.measurement);}
 const {raw,...exeVerification}=E.verifyExe();T.validateDerived(v.temporalKnowledge,v.temporalDerived,{...evidence,raw});const riffVerification=D.I.python(['--verify']);const out=await C.measured(()=>C.publish(owned(store),id,options));return {...out,numericalReplay,exeVerification,riffVerification,totalMilliseconds:performance.now()-start,acceptedUtc:new Date().toISOString(),timeBasis:'Proof execution publication completion receipt, not physical observation/source date'};
}
export async function pin(store,id){await initialize();const snapshot=resolveGeneration(store,id,{hydrate:true}),generation=snapshot.generation;return {generation,snapshot,query:q=>{const fresh=resolveGeneration(store,generation,{hydrate:true}),counters={},answer=T.query(fresh.value.temporalKnowledge,q,counters);C.count('temporalPredicates',counters.temporalPredicates??0);C.count('temporalRowsInspected',counters.revisionRecordsInspected);return {generation,members:fresh.publication.members,...answer,counters};},derived:(k=snapshot.value.temporalKnowledge.ordinal)=>{const fresh=resolveGeneration(store,generation,{hydrate:true});return {generation,knowledgeCutoff:k,results:T.derivedAt(fresh.value.temporalKnowledge,fresh.value.temporalDerived,k)};},close:async()=>{}};}
