// Finite revision ledger, qualified temporal predicates, and three existing Exe summary receipts.
import fs from 'node:fs';import {join} from 'node:path';
import {plan,need,digest,clone,loadEvidence,fullNativeSummary} from './evidence.mjs';
export {plan,digest};
const HEX=/^[a-f0-9]{64}$/;
export function timeBounds(t){need(t&&['unknown','instant','epoch','interval'].includes(t.kind),'Invalid temporal extent');if(t.kind==='unknown'){need(typeof t.reason==='string'&&t.reason.length>0,'Unknown needs reason');return null;}
 need(['year','month','day','second'].includes(t.precision)&&typeof t.basis==='string','Unsupported timestamp precision');
 function date(v,end=false){const formats={year:/^\d{4}$/,month:/^\d{4}-\d{2}$/,day:/^\d{4}-\d{2}-\d{2}$/,second:/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/};need(typeof v==='string'&&formats[t.precision].test(v),'Unsupported timestamp precision');const d=new Date(t.precision==='year'?v+'-01-01T00:00:00Z':t.precision==='month'?v+'-01T00:00:00Z':t.precision==='day'?v+'T00:00:00Z':v);need(Number.isFinite(+d),'Invalid date');if(t.precision==='second'){const localDay=v.slice(0,10),calendar=new Date(localDay+'T00:00:00Z');need(Number.isFinite(+calendar)&&calendar.toISOString().startsWith(localDay),'Invalid calendar date');}if(t.precision!=='second')need(d.toISOString().startsWith(v),'Invalid calendar date');if(end){if(t.precision==='year')d.setUTCFullYear(d.getUTCFullYear()+1);else if(t.precision==='month')d.setUTCMonth(d.getUTCMonth()+1);else if(t.precision==='day')d.setUTCDate(d.getUTCDate()+1);else return +d;}return +d;}
 if(t.kind==='interval'){const a=date(t.start),z=date(t.end);need(a<=z,'Invalid interval ordering');return [a,date(t.end,true)];}const a=date(t.value);return [a,date(t.value,true)];}
function dateQuery(v){const precision=v.includes('T')?'second':v.length===4?'year':v.length===7?'month':'day';return timeBounds({kind:'epoch',value:v,precision,basis:'Explicit query precision'});}
export function visible(ledger,k=ledger.ordinal){need(Number.isSafeInteger(k)&&k>=0&&k<=ledger.ordinal,'Knowledge cutoff beyond pin or invalid');const selected=new Map();for(const r of ledger.records.filter(r=>r.knowledge.ordinal<=k).sort((a,b)=>a.knowledge.ordinal-b.knowledge.ordinal))selected.set(r.assignment,r);return [...selected.values()].sort((a,b)=>a.assignment.localeCompare(b.assignment));}
export function query(ledger,q,counters={}){need(q&&typeof q==='object'&&!Array.isArray(q),'Malformed query');const allowed=['id','knowledge','region','assignment','feature','physical','unknown','sourcePeriod','mode'];need(Object.keys(q).every(k=>allowed.includes(k)),'Unsupported query field');need(!q.region||['tryfan','riffelhorn','exe'].includes(q.region),'Invalid region');need(!q.unknown||['physical','source'].includes(q.unknown),'Invalid unknown axis');need(!q.mode||['overlap','valid-throughout'].includes(q.mode),'Unsupported temporal mode');let range=null;
 if(q.physical){need(Object.keys(q.physical).sort().join(',')==='end,role,start'&&['observation','event','survey','nominal-epoch','asserted-validity'].includes(q.physical.role),'Incompatible temporal qualifier');range=[dateQuery(q.physical.start)[0],dateQuery(q.physical.end)[1]];need(range[0]<=dateQuery(q.physical.end)[0],'Invalid query interval ordering');}
 let sourceRange=null;if(q.sourcePeriod){need(Array.isArray(q.sourcePeriod)&&q.sourcePeriod.length===2,'Invalid source period');sourceRange=[dateQuery(q.sourcePeriod[0])[0],dateQuery(q.sourcePeriod[1])[1]];need(sourceRange[0]<=dateQuery(q.sourcePeriod[1])[0],'Invalid query interval ordering');}
 const matches=[],indeterminate=[];counters.revisionRecordsInspected=ledger.records.length;
 for(const r of visible(ledger,q.knowledge)){if(q.region&&r.region!==q.region||q.assignment&&r.assignment!==q.assignment||q.feature&&r.feature!==q.feature)continue;counters.sourceQualificationChecks=(counters.sourceQualificationChecks??0)+1;
  if(q.unknown&&(q.unknown==='physical'?r.physical.extent:r.sourceTime).kind!=='unknown')continue;
  let unknown=false,ok=true;
  if(range){counters.temporalPredicates=(counters.temporalPredicates??0)+1;const t=r.physical.extent,b=timeBounds(t);if(!b)unknown=true;else if(q.mode==='valid-throughout'){unknown=true;}else if(r.physical.role!==q.physical.role)ok=false;else ok=b[0]===b[1]?b[0]>=range[0]&&b[0]<range[1]||b[0]===range[0]&&range[0]===range[1]:range[0]===range[1]?b[0]<=range[0]&&range[0]<b[1]:b[0]<range[1]&&range[0]<b[1];}
  if(sourceRange){counters.temporalPredicates=(counters.temporalPredicates??0)+1;const b=timeBounds(r.sourceTime);if(!b)unknown=true;else ok=ok&&(b[0]===b[1]?(sourceRange[0]<=b[0]&&b[0]<sourceRange[1]||sourceRange[0]===sourceRange[1]&&sourceRange[0]===b[0]):sourceRange[0]===sourceRange[1]?b[0]<=sourceRange[0]&&sourceRange[0]<b[1]:b[0]<sourceRange[1]&&sourceRange[0]<b[1]);}
  if(ok)(unknown?indeterminate:matches).push(r);
 }
 counters.matches=matches.length;counters.indeterminate=indeterminate.length;return {schema:'atlas-qualified-temporal-answer/v1',knowledgeCutoff:q.knowledge??ledger.ordinal,matches,indeterminate,limitations:'No match is not physical absence. Overlap describes source time support, never continuous physical validity or physical change.'};}
export const correctionAssignments=['exe:2024-03:point','exe:2024-03:support','riffelhorn:'+plan.selected.riffelhorn.find(x=>x.startsWith('dtm:'))];
function record(anchor,k,acceptedUtc,supersedes=null){const body={...clone(anchor),knowledge:{ordinal:k,event:k===0?'initial':k===1?'late-March':k===2?'controlled-correction':'late-September',acceptedUtc,basis:'Actual proof execution clock; controlled knowledge ordering, not historical source acquisition'},supersedes,...(k===2?{correction:{kind:'controlled-qualification',reason:plan.correction.meaning,scope:anchor.region==='riffelhorn'?plan.correction.riffelhorn.bounds:anchor.support}}:{})};return {...body,revision:digest(body)};}
export function transition(ledger,e,stage,acceptedUtc=new Date().toISOString()){need(stage===(ledger?.ordinal??-1)+1&&stage<=4,'Knowledge revision ordered incorrectly');const next=ledger?clone(ledger):{schema:'atlas-temporal-knowledge/v1',ordinal:-1,records:[],events:[]};next.ordinal=stage;next.events.push({ordinal:stage,event:plan.sequence[stage].event,acceptedUtc,basis:'Controlled sequence executed now; source physical history unchanged'});
 const ids=stage===0?Object.keys(e.anchors).filter(id=>!id.includes('2024-03')&&!id.includes('2024-09')):stage===1?['exe:2024-03:point','exe:2024-03:support']:stage===2?correctionAssignments:stage===3?['exe:2024-09:point','exe:2024-09:support']:[];
 for(const id of ids){const old=next.records.filter(r=>r.assignment===id).at(-1);next.records.push(record(e.anchors[id],stage,acceptedUtc,stage===2?old?.revision:null));}return next;}
export function validateLedger(ledger,e){need(ledger.schema==='atlas-temporal-knowledge/v1'&&Number.isSafeInteger(ledger.ordinal)&&ledger.ordinal>=0&&ledger.ordinal<=4,'Invalid knowledge ledger');need(ledger.events.length===ledger.ordinal+1&&ledger.events.every((v,i)=>v.ordinal===i&&v.event===plan.sequence[i].event&&Number.isFinite(Date.parse(v.acceptedUtc))),'Knowledge revision ordered incorrectly');const rebuilt=[];
 for(let k=0;k<=ledger.ordinal;k++){const prior=k?{schema:ledger.schema,ordinal:k-1,records:clone(rebuilt),events:ledger.events.slice(0,k)}:null;const expected=transition(prior,e,k,ledger.events[k].acceptedUtc);rebuilt.splice(0,rebuilt.length,...expected.records);}
 need(encodeLocal(rebuilt)===encodeLocal(ledger.records),'Invalid source/revision identity, supersession or duplicate/missing evidence');const seen=new Set(),latest=new Map();for(const r of ledger.records){need(HEX.test(r.revision)&&r.revision===digest(Object.fromEntries(Object.entries(r).filter(([k])=>k!=='revision')))&&!seen.has(r.revision),'Invalid/duplicate revision identity');seen.add(r.revision);need(r.knowledge.ordinal<=ledger.ordinal,'Future knowledge');timeBounds(r.physical.extent);timeBounds(r.sourceTime);timeBounds(r.retention);timeBounds(r.preparation);need(['observation','survey','nominal-epoch','event','asserted-validity'].includes(r.physical.role),'Incompatible temporal qualifier');if(r.supersedes)need(latest.get(r.assignment)===r.supersedes,'Correction without supersession lineage');else need(!latest.has(r.assignment),'Ambiguous observation identity');latest.set(r.assignment,r.revision);}return true;}
import {encode as encodeLocal} from '../../../pilots/atlas/tryfan/identity.mjs';
export function summaryInputs(ledger,k=ledger.ordinal){const rows=visible(ledger,k),refs=m=>rows.find(r=>r.assignment==='exe:'+m+':support');return Object.fromEntries([['2024-03',[refs('2024-03')]],['2024-09',[refs('2024-09')]],['pair',[refs('2024-03'),refs('2024-09')]]].filter(([,a])=>a.every(Boolean)).map(([key,a])=>[key,a.map(r=>r.revision)]));}
export function emptyDerived(){return {schema:'atlas-temporal-derived/v1',receipts:{},current:{}};}
export function recompute(ledger,old,e,{full=false}={}){const began=performance.now(),next=clone(old),inputs=summaryInputs(ledger),changed=[];next.current={};for(const [slot,refs]of Object.entries(inputs)){const body={slot,method:e.native.method,inputRevisions:refs,native:fullNativeSummary(e,slot),qualifications:refs.map(id=>{const r=ledger.records.find(r=>r.revision===id);return {physical:r.physical,lineage:r.lineage,qualification:r.qualification,...(r.correction?{correction:r.correction}:{} )};})},id=digest(body);if(full||!next.receipts[id]){next.receipts[id]={...body,revision:id};changed.push(slot);}next.current[slot]=id;}return {state:next,measurement:{milliseconds:performance.now()-began,recomputed:changed.length,changed,receiptInputsInspected:Object.values(inputs).reduce((n,a)=>n+a.length,0),payloadReads:0,basis:'Qualified retained native query facts, reconstructed from actual payloads at evidence setup; publication fresh replay rereads them'}};}
export function currentDerived(state){return Object.fromEntries(Object.entries(state.current).map(([slot,id])=>[slot,state.receipts[id]]));}
export function derivedAt(ledger,state,k){const refs=summaryInputs(ledger,k),out={};for(const [slot,input]of Object.entries(refs)){const found=Object.values(state.receipts).find(r=>r.slot===slot&&encodeLocal(r.inputRevisions)===encodeLocal(input));need(found,'Historical derived revision unavailable');out[slot]=found;}return out;}
export function validateDerived(ledger,state,e){need(state.schema==='atlas-temporal-derived/v1','Invalid temporal derived schema');for(const [id,r]of Object.entries(state.receipts)){need(id===r.revision&&digest(Object.fromEntries(Object.entries(r).filter(([k])=>k!=='revision')))===id,'Invalid derived receipt identity');need(r.inputRevisions.every(ref=>ledger.records.some(r=>r.revision===ref)),'Missing historical dependency');need(encodeLocal(r.method)===encodeLocal(e.native.method)&&encodeLocal(r.native)===encodeLocal(fullNativeSummary(e,r.slot)),'Method/native summary mismatch');const qualifications=r.inputRevisions.map(id=>{const x=ledger.records.find(r=>r.revision===id);return {physical:x.physical,lineage:x.lineage,qualification:x.qualification,...(x.correction?{correction:x.correction}:{} )};});need(encodeLocal(r.qualifications)===encodeLocal(qualifications),'Qualification propagation mismatch');}need(encodeLocal(currentDerived(state))===encodeLocal(currentDerived(recompute(ledger,emptyDerived(),e,{full:true}).state)),'Stale/incomplete temporal derived closure');for(let k=0;k<=ledger.ordinal;k++)derivedAt(ledger,state,k);return true;}
export function bundle(ledger){const resources=[],collections=[],definitions=[{id:'temporal:qualified-metadata',revision:'1',kind:'property',vocabulary:{id:'Bounded temporal metadata proof',version:{status:'known',value:'1'}},label:'Source-qualified retained temporal evidence',meaning:'Descriptor preserves exact native evidence record; no new physical inference',reference:{href:'docs/research/atlas-temporal-integration.md'},valueKinds:['descriptor']}];
 for(const r of visible(ledger)){const ref={kind:'product',id:r.assignment,revision:{status:'known',value:r.revision}},rights={licence:{status:'unknown',reason:'Family-specific actual terms remain attached to unchanged native lineage'},attribution:['Exact source-native credits in qualification/lineage'],references:['docs/research/atlas-temporal-integration.md'],limitations:'This projection is not a replacement licence; full original rights attached'};const source={id:'temporal-input:'+r.assignment,kind:'source',revision:{status:'known',value:digest(r.lineage)}};resources.push({ref:source,domain:'semantics',name:'Exact retained lineage reference; not a claim of upstream authenticity',definition:{href:'docs/research/atlas-temporal-integration.md',selector:r.assignment},rights,inputs:[]});resources.push({ref,domain:'semantics',name:r.assignment,definition:{href:'docs/research/atlas-temporal-integration.md',selector:r.revision},rights,dates:[...(['unknown'].includes(r.sourceTime.kind)?[]:[{role:'publication',extent:r.sourceTime}]),...(['unknown'].includes(r.retention.kind)?[]:[{role:'retrieval',extent:r.retention}])],inputs:[source]});collections.push({id:'temporal:'+r.assignment,revision:r.revision,product:ref,representation:'records',context:{support:r.support,time:[r.physical],evidence:{modes:['derived'],description:'Qualified metadata wrapper over native record/support, not a new observation',inputs:[{kind:'resource',ref,role:'Exact retained assignment/provenance wrapper'}],completeness:'partial',limitations:'Physical/source/retention/knowledge/publication distinct; actual native meaning remains attached.',processing:[{method:'qualified-time-metadata-projection',revision:{status:'known',value:shaFile()},record:{href:'scripts/atlas/temporal-integration/model.mjs'},parameters:{physicalTimeFromNative:true}}]}},claims:[{id:'temporal-claim:'+r.assignment,revision:r.revision,native:{property:{id:'temporal:qualified-metadata',revision:'1'},fields:{region:r.region,assignment:r.assignment}},result:{kind:'assertion',value:{kind:'descriptor',text:encodeLocal(r)}},record:{href:'docs/research/atlas-temporal-integration.md',selector:r.revision}}]});}return {contract:'atlas-semantic-evidence/v1',definitions,resources,collections,mappings:[]};}

function shaFile(){return digest(fs.readFileSync(new URL(import.meta.url),'utf8'));}
