import fs from 'node:fs';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import * as A from './integration.mjs';import {encode,sha} from '../../../pilots/atlas/tryfan/identity.mjs';
import {ROOT,DATA} from '../../../pilots/atlas/tryfan/catalogue.mjs';
const matrix=JSON.parse(fs.readFileSync(join(A.E.H,'matrix.json'),'utf8')),store=join(A.T.plan.stateRoot,'measured-'+Date.now());
const began=performance.now(),seed=await A.seed(store),e=await A.E.loadEvidence();let value=seed.value;const history=[],members=[],roots=[],publications=[],updates=[],queries=[],answerHashes=[],queryMatrix=[],observations=[],derivedKnowledge=[];
function oracle(ledger,qs){const p=spawnSync(join(DATA,'earth-lab/.venv/Scripts/python.exe'),[join(A.E.H,'oracle.py')],{cwd:ROOT,input:JSON.stringify({ledger,queries:qs}),maxBuffer:32*1024*1024,encoding:'utf8',env:{...process.env,PYTHONIOENCODING:'utf-8'}});A.E.need(p.status===0,p.stderr);return JSON.parse(p.stdout);}
function strip({generation,members,counters,...answer}){return answer;}
function manual(v,stage){const l=v.temporalKnowledge;A.E.need(A.T.visible(l).length===matrix.manualExpectations.currentByStage[stage]&&l.records.length===matrix.manualExpectations.retainedByStage[stage],'Frozen population expectations failed');const march=A.T.query(l,matrix.queries.find(q=>q.id==='march'));A.E.need(march.matches.length===(stage===0?0:2),'G0/G1 March knowledge expectation failed');const sept=A.T.query(l,matrix.queries.find(q=>q.id==='september'));A.E.need(sept.matches.length===(stage<3?0:2),'September distinct-period expectation failed');const support=A.T.visible(l).find(r=>r.assignment==='exe:2024-03:support');if(support)A.E.need(encode(support.nativeRecord.counts)===encode(matrix.manualExpectations.MarchCounts),'Frozen March source counts changed');const s=A.T.visible(l).find(r=>r.assignment==='exe:2024-09:support');if(s)A.E.need(encode(s.nativeRecord.counts)===encode(matrix.manualExpectations.SeptemberCounts),'Frozen September source counts changed');if(stage>=2){const corrected=A.T.visible(l).filter(r=>r.supersedes);A.E.need(corrected.length===3,'Three controlled corrections required');for(const r of corrected){const old=l.records.find(a=>a.revision===r.supersedes);A.E.need(r.assignment===old.assignment&&encode(r.physical)===encode(old.physical)&&encode(r.nativeRecord)===encode(old.nativeRecord),'Correction invented new observation/value/time');}}}
for(let stage=0;stage<5;stage++){
 if(stage){const runs=[];for(let rep=0;rep<3;rep++){const r=await A.revise(value,stage);runs.push(r.measurement);if(rep===0)var next=r.value;}value=next;updates.push({stage,runs});}
 manual(value,stage);const previous=history.at(-1)??null,g= A.prepare(store,value,seed.locators,{ordinal:stage+1,predecessor:previous});
 if(previous){const p=await A.pin(store,previous);A.E.need(A.E.digest(strip(p.query({id:'all'})))===observations.at(-1).allHash,'Old pinned state changed while staged');try{await A.pin(store,g);throw Error('Staged exposed');}catch(err){A.E.need(err.code==='generation-unpublished','Staged failure wrong: '+err.message);}}
 const p=await A.publish(store,g);publications.push(p);history.push(g);roots.push(A.current(store));const pin=await A.pin(store,g);members.push(pin.snapshot.publication.members);observations.push({stage,current:A.T.visible(value.temporalKnowledge).length,records:value.temporalKnowledge.records.length,allHash:A.E.digest(strip(pin.query({id:'all'}))),supersessions:value.temporalKnowledge.records.filter(r=>r.supersedes).length,temporalResults:Object.keys(value.temporalDerived.current).length});
 const extra=stage?matrix.additionalKnowledgeQueries['stage'+stage].map(k=>({id:'march-as-known-'+k,knowledge:k,region:'exe',physical:{start:'2024-03-01',end:'2024-03-31',role:'observation'}})):[],qs=[...matrix.queries,...extra],ref=oracle(value.temporalKnowledge,qs);queryMatrix.push(qs);answerHashes.push(A.E.digest(ref));
 for(let rep=0;rep<3;rep++)for(const [i,q]of qs.entries()){const result=await A.measured(()=>pin.query(q)),answer=strip(result.value);A.E.need(encode(answer)===encode(ref[i]),'Independent qualified oracle mismatch '+q.id);queries.push({stage,repeat:rep,id:q.id,agreement:true,hash:A.E.digest(answer),matches:answer.matches.length,indeterminate:answer.indeterminate.length,counters:result.value.counters,measurement:result.measurement});}
 for(let k=0;k<=stage;k++){const d=pin.derived(k),input=A.T.summaryInputs(value.temporalKnowledge,k);A.E.need(Object.keys(d.results).sort().join(',')===Object.keys(input).sort().join(','),'Knowledge-derived history incorrectly includes later periods');for(const [slot,r]of Object.entries(d.results))A.E.need(encode(r.inputRevisions)===encode(input[slot]),'Knowledge-derived input mismatch');derivedKnowledge.push({stage,knowledge:k,slots:Object.keys(d.results),revisions:Object.values(d.results).map(r=>r.revision)});}
 console.log('published',stage,g,'queries',qs.length);
}
const replayFile=join(store,'replay.json');fs.writeFileSync(replayFile,encode({history,queryMatrix,answerHashes}));const fresh=[];for(let n=0;n<3;n++){const p=spawnSync(process.execPath,[join(A.E.H,'worker.mjs'),'replay',store,replayFile],{cwd:ROOT,encoding:'utf8',maxBuffer:8*1024*1024,timeout:180000});A.E.need(p.status===0,p.stderr);fresh.push(JSON.parse(p.stdout));console.log('fresh-replay',n+1);}
const footprints={};for(const dir of ['components','publications','membership','artifacts']){const f=fs.readdirSync(join(store,dir));footprints[dir]={files:f.length,bytes:f.reduce((n,p)=>n+fs.statSync(join(store,dir,p)).size,0)};}
const rawQueryFile=join(store,'queries.json');fs.writeFileSync(rawQueryFile,JSON.stringify(queries)+'\n');const groupedQueries=[];for(const q of queries.filter(q=>q.repeat===0)){const runs=queries.filter(x=>x.stage===q.stage&&x.id===q.id);groupedQueries.push({...q,repeat:undefined,milliseconds:runs.map(x=>x.measurement.milliseconds),measurement:{reads:q.measurement.reads,counters:q.measurement.counters},RSS:runs.map(x=>x.measurement.RSSAfter)});}
const engine=['evidence.mjs','model.mjs','integration.mjs','oracle.py','worker.mjs','prove.mjs'];const out={schema:'atlas-temporal-integration-results/v1',startingCheckpoint:A.T.plan.startingCheckpoint,planSha256:sha(fs.readFileSync(join(A.E.H,'plan.json'))),matrixSha256:sha(fs.readFileSync(join(A.E.H,'matrix.json'))),implementationHashes:Object.fromEntries(engine.map(p=>[p,sha(fs.readFileSync(join(A.E.H,p)))])),store,setup:seed.setup,history,roots,members,observations,updates,publications,query:groupedQueries,queryComparisons:queries.length,rawQueries:{path:rawQueryFile,sha256:sha(fs.readFileSync(rawQueryFile)),bytes:fs.statSync(rawQueryFile).size},derivedKnowledge,fresh,footprint:footprints,totalMilliseconds:performance.now()-began,retained:{realAssignments:17,initialAssignments:13,finalRevisionRows:20,controlledSupersessions:3,acceptedRegionalDerived:184,ExeVerifiedSourceFiles:31,ExeVerifiedSourceBytes:9892590},agreement:true,decision:'C - PROOF SUCCESS',limitations:['Controlled acceptance sequence, not historical global Atlas ingestion','No corrected physical observation/code; qualification only','Unknown exact survey/cell/publication/preparation times remain unknown','Full source validation and complete numerical replay remain publication-wide','Full metadata hydration, uncontrolled OS cache, sampled Node RSS excludes Python peak','Bounded local single-writer; no production/event database']};
fs.writeFileSync(join(ROOT,'docs/research/atlas-temporal-integration-results.json'),JSON.stringify(out)+'\n');console.log('complete',out.decision,queries.length,'queries',store);
