import test,{before} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {join} from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {createInterface} from 'node:readline';
import * as A from './integration.mjs';import {encode} from '../../../pilots/atlas/tryfan/identity.mjs';import {ROOT} from '../../../pilots/atlas/tryfan/catalogue.mjs';
let run,e,store,values;
before(async()=>{e=await A.initialize();run=JSON.parse(fs.readFileSync(join(ROOT,'docs/research/atlas-temporal-integration-results.json'),'utf8'));store=run.store;values=run.history.map(g=>A.resolveGeneration(store,g,{hydrate:true}).value);});
const march={region:'exe',physical:{start:'2024-03-01',end:'2024-03-31',role:'observation'}};
function copied(label,stage=4){const path=join(A.T.plan.stateRoot,'negative-'+label+'-'+Date.now());fs.cpSync(store,path,{recursive:true});A.owned(path);if(stage<4)fs.writeFileSync(join(path,'current.json'),encode(run.roots[stage]));return path;}
function badLedger(fn){const l=structuredClone(values[4].temporalKnowledge);fn(l);return ()=>A.T.validateLedger(l,e);}
test('real retained selection and temporal completeness are accountable',()=>{assert.equal(Object.keys(e.anchors).length,17);assert.equal(e.setup.verifiedExeFiles,31);assert.equal(e.setup.verifiedExeBytes,9892590);assert.equal(e.anchors['tryfan:appearance'].physical.extent.value,'2026-07-12T11:33:31.024Z');});
test('late March arrival never retroactively enters G0',async()=>{const a=await A.pin(store,run.history[0]),b=await A.pin(store,run.history[1]);assert.equal(a.query(march).matches.length,0);assert.equal(b.query(march).matches.length,2);assert.equal(b.query({...march,knowledge:0}).matches.length,0);});
test('distinct observation periods preserve native gap and non-detection',()=>{const r=A.T.visible(values[4].temporalKnowledge);assert.equal(r.find(x=>x.assignment==='exe:2024-03:point').nativeRecord.result.value.outcome,'detected');assert.equal(r.find(x=>x.assignment==='exe:2024-09:point').nativeRecord.result.reason,'no-observation');assert.deepEqual(r.find(x=>x.assignment==='exe:2024-09:support').nativeRecord.counts,{'0':76,'1':1,'2':0});});
test('same-assignment correction preserves physical time/support/value and old revision',()=>{const l=values[4].temporalKnowledge;for(const r of l.records.filter(r=>r.supersedes)){const old=l.records.find(x=>x.revision===r.supersedes);assert.equal(r.assignment,old.assignment);assert.deepEqual(r.physical,old.physical);assert.deepEqual(r.nativeRecord,old.nativeRecord);assert.deepEqual(r.support,old.support);assert.notEqual(r.revision,old.revision);}assert.equal(l.records.filter(r=>r.supersedes).length,3);});
test('as-known-at differs from physical-time and publication-generation',async()=>{const p=await A.pin(store,run.history[4]),a=p.query({...march,knowledge:1}),b=p.query({...march,knowledge:2});assert.equal(a.matches.length,2);assert.equal(b.matches.length,2);assert.notEqual(a.matches[0].revision,b.matches[0].revision);assert.deepEqual(a.matches[0].physical,b.matches[0].physical);assert.throws(()=>A.T.query(values[1].temporalKnowledge,{knowledge:2}),/beyond pin/);});
test('source publication can be known when physical time is unknown',()=>{const r=e.anchors['exe:wfd'];assert.equal(r.sourceTime.value,'2025-06-23');assert.equal(r.physical.extent.kind,'unknown');const q=A.T.query(values[4].temporalKnowledge,{assignment:'exe:wfd',physical:{start:'2025-06-23',end:'2025-06-23',role:'observation'}});assert.equal(q.matches.length,0);assert.equal(q.indeterminate.length,1);});
test('edition/year and locator modification are not source publication clocks',()=>{for(const id of Object.keys(e.anchors).filter(x=>x.includes(':dtm:')||x.includes(':worldcover:')||x.includes('2024-03')||x.includes('2024-09')))assert.equal(e.anchors[id].sourceTime.kind,'unknown');});
test('real retention is distinct from month and controlled acceptance',()=>{const r=A.T.visible(values[4].temporalKnowledge).find(r=>r.assignment==='exe:2024-03:point');assert.equal(r.physical.extent.start,'2024-03-01');assert.equal(r.retention.value,'2026-10-06T11:18:17.064598+00:00');assert.equal(r.knowledge.ordinal,2);assert.equal(r.preparation.kind,'unknown');});
test('year survey remains broad, not a fabricated daily observation',()=>{const q=A.T.query(values[4].temporalKnowledge,{region:'riffelhorn',physical:{start:'2016-12-31',end:'2016-12-31',role:'survey'}});assert.equal(q.matches.length,6);assert.ok(q.matches.every(r=>r.physical.extent.precision==='year'&&r.physical.extent.value==='2016'));});
test('event interval includes endpoint without prolonging to current state',()=>{const l=values[4].temporalKnowledge;assert.equal(A.T.query(l,{feature:'rfo:31383',physical:{start:'2014-02-05',end:'2014-02-05',role:'event'}}).matches.length,1);assert.equal(A.T.query(l,{feature:'rfo:31383',physical:{start:'2026-10-08',end:'2026-10-08',role:'event'}}).matches.length,0);});
test('unknown times return explicit indeterminate and continuous validity is unsupported',()=>{const l=values[4].temporalKnowledge;assert.equal(A.T.query(l,{assignment:'tryfan:terrain',physical:{start:'2024-01-01',end:'2024-12-31',role:'observation'}}).indeterminate.length,1);assert.equal(A.T.query(l,{assignment:'exe:2024-03:point',...march,mode:'valid-throughout'}).matches.length,0);});
test('unknown source time is separately queryable',()=>{const q=A.T.query(values[4].temporalKnowledge,{unknown:'source'});assert.ok(q.matches.length>0);assert.ok(q.matches.every(r=>r.sourceTime.kind==='unknown'));});
test('invalid interval ordering and impossible calendar dates reject',()=>{assert.throws(()=>A.T.timeBounds({kind:'interval',start:'2024-09-30',end:'2024-03-01',precision:'day',basis:'negative'}),/ordering/);assert.throws(()=>A.T.timeBounds({kind:'epoch',value:'2024-02-30',precision:'day',basis:'negative'}),/calendar/);});
test('unsupported timestamp precision rejects',()=>assert.throws(()=>A.T.timeBounds({kind:'instant',value:'2015',precision:'second',basis:'invented precision'}),/precision/));
test('incompatible temporal qualifier and reversed query interval reject',()=>{assert.throws(()=>A.T.query(values[4].temporalKnowledge,{physical:{start:'2024-01-01',end:'2024-01-01',role:'geological-age'}}),/qualifier/);assert.throws(()=>A.T.query(values[4].temporalKnowledge,{physical:{start:'2025-01-01',end:'2024-01-01',role:'observation'}}),/ordering/);});
test('observation identity is not merged by location or value',()=>{const a=e.anchors['exe:2024-03:point'],b=e.anchors['exe:2024-09:point'];assert.deepEqual(a.support,b.support);assert.notEqual(a.assignment,b.assignment);assert.throws(badLedger(l=>l.records[0].assignment='exe:2024-03:point'),/identity|evidence/);});
test('correction without valid supersession lineage rejects',()=>assert.throws(badLedger(l=>l.records.find(r=>r.supersedes).supersedes=null),/supersession|identity/));
test('missing evidence and duplicate revision identity reject',()=>{assert.throws(badLedger(l=>l.records.pop()),/missing evidence|identity/);assert.throws(badLedger(l=>l.records.push(l.records[0])),/duplicate|identity/);});
test('incorrect knowledge order and future claim reject',()=>{assert.throws(badLedger(l=>l.events[1].ordinal=3),/ordered/);assert.throws(badLedger(l=>l.records[0].knowledge.ordinal=9),/identity|Future/);});
test('frozen semantic projection preserves qualified records and provenance',()=>{for(const v of values)assert.deepEqual(e.validateSemantic(A.T.bundle(v.temporalKnowledge)),[]);const r=A.T.visible(values[4].temporalKnowledge).find(r=>r.assignment==='exe:2024-03:point');assert.equal(r.lineage.source.sha256,'336c5746c4d1145bf212fa65b7c2ff11d7f5691b17ded1d6eb7127a72ca311c6');assert.match(r.qualification.rights.attribution.join(' '),/JRC/);});
test('scoped regional closure exactly8; other region and176 branches reused',()=>{for(const u of run.updates.find(u=>u.stage===2).runs){assert.equal(u.regional.recomputed,8);assert.equal(u.regional.expected.length,8);assert.equal(u.regional.reuse,176);}assert.deepEqual(values[0].tryfanDerived,values[4].tryfanDerived);assert.deepEqual(values[0].tryfanDependencyState,values[4].tryfanDependencyState);});
test('qualification-only derived revisions preserve numerical values',()=>{const old=values[0].riffelhornDerived,newer=values[4].riffelhornDerived;for(const [id,rev]of Object.entries(old.active)){const a=old.results[rev],b=newer.results[newer.active[id]];assert.deepEqual(a.value,b.value);assert.deepEqual(a.support,b.support);}assert.notDeepEqual(old.active,newer.active);});
test('publication-only metadata note requires no numerical recomputation',()=>{assert.ok(run.updates.find(u=>u.stage===4).runs.every(r=>r.temporal.recomputed===0&&r.regional.recomputed===0));assert.equal(run.members[3].temporalDerived,run.members[4].temporalDerived);assert.equal(run.members[3].riffelhornDerived,run.members[4].riffelhornDerived);});
test('old temporal summaries remain eligible only with old exact knowledge inputs',async()=>{const p=await A.pin(store,run.history[4]);assert.notEqual(p.derived(1).results['2024-03'].revision,p.derived(2).results['2024-03'].revision);assert.equal(Object.keys(p.derived(1).results).length,1);assert.equal(Object.keys(p.derived(3).results).length,3);});
test('missing historical summary and stale current receipts reject',()=>{const st=structuredClone(values[4].temporalDerived),old=Object.values(st.receipts).find(r=>r.slot==='2024-03'&&r.revision!==st.current['2024-03']);delete st.receipts[old.revision];assert.throws(()=>A.T.validateDerived(values[4].temporalKnowledge,st,e),/Historical/);const b=structuredClone(values[2]);b.temporalDerived=values[1].temporalDerived;assert.throws(()=>A.prepare(store,b,e.base.locators,{ordinal:3,predecessor:run.history[1]}),/Stale/);});
test('stale regional results, incomplete temporal closure and cross-region leakage cannot stage',()=>{for(const change of [v=>{v.riffelhornDerived=values[0].riffelhornDerived;},v=>{delete v.temporalDerived.current['2024-09'];},v=>{v.tryfanDependencyState.adminRevision++;}]){const v=structuredClone(values[4]);change(v);assert.throws(()=>A.prepare(store,v,e.base.locators,{ordinal:5,predecessor:run.history[3]}));}assert.equal(A.current(store).generation,run.history[4]);});
test('missing component membership rejects without root advancement',async()=>{const s=copied('membership'),p=structuredClone(A.resolveGeneration(s,run.history[4]).publication);p.predecessor=run.history[4];p.members.temporalKnowledge='0'.repeat(64);const id=A.E.digest(p);fs.writeFileSync(join(s,'publications',id+'.json'),encode(p));await assert.rejects(A.publish(s,id),/unavailable/);assert.equal(A.current(s).generation,run.history[4]);});
test('historical component unavailable fails old pin but not current',async()=>{const s=copied('old-component'),id=run.members[0].temporalKnowledge;assert.notEqual(id,run.members[4].temporalKnowledge);fs.unlinkSync(join(s,'components',id+'.json'));await assert.rejects(A.pin(s,run.history[0]),/unavailable/);assert.equal((await A.pin(s,run.history[4])).generation,run.history[4]);});
test('history lookup never needs intervening publication ancestry',async()=>{const s=copied('ancestor');fs.unlinkSync(join(s,'publications',run.history[2]+'.json'));for(const g of [run.history[0],run.history[4]]){const p=await A.pin(s,g),q=await A.measured(()=>p.query(march));assert.equal(q.measurement.counters.ancestryTraversals,0);assert.equal(q.measurement.counters.membershipVisits,33);assert.equal(q.measurement.counters.componentEdges,13);}});
test('same pin supports native queries across both unchanged regional registrations',async()=>{const p=await A.D.I.pin(store,run.history[4]);try{const q=await p.query([{region:'tryfan',query:{place:{crs:'EPSG:27700',point:[266405,359387]},property:'derived-slope'}},{region:'riffelhorn',query:{point:[2624500,1091500],families:['dtm']}}]);assert.ok(q.answers.every(a=>a.generation===run.history[4]));assert.equal(q.answers[1].native.preparedRevision,A.D.I.plan.regions.riffelhorn.preparedRevision);}finally{await p.close();}});
function consumer(s,g){const c=spawn(process.execPath,[join(A.E.H,'worker.mjs'),'consumer',s,g],{stdio:['pipe','pipe','pipe']});let resolveReady,rejectReady,queue=[],stderr='';const ready=new Promise((r,j)=>{resolveReady=r;rejectReady=j;});c.stderr.on('data',d=>stderr+=d);createInterface({input:c.stdout}).on('line',line=>{const v=JSON.parse(line);if(v.ready)resolveReady(v);else{const p=queue.shift();if(v.error)p.reject(Error(v.error));else p.resolve(v.answer);}});c.on('error',rejectReady);c.on('exit',code=>{if(code)rejectReady(Error(stderr));});return {ready,query:q=>new Promise((resolve,reject)=>{queue.push({resolve,reject});c.stdin.write(JSON.stringify(q)+'\n');}),close:()=>c.exitCode!==null?Promise.resolve():new Promise(resolve=>{c.once('exit',resolve);c.stdin.end();})};}
test('separate consumer stays pinned during staging and new publication',async()=>{const s=copied('pin',3),p=consumer(s,run.history[1]);await p.ready;try{const before=await p.query(march);await assert.rejects(A.pin(s,run.history[4]),/committed|pre-switch/);assert.deepEqual(await p.query(march),before);await A.publish(s,run.history[4]);assert.deepEqual(await p.query(march),before);const current=await A.pin(s);assert.notEqual(current.query(march).matches[0].revision,before.matches[0].revision);}finally{await p.close();}});
test('abrupt pre-switch temporal publication preserves root and fresh history; retry succeeds',async()=>{const s=copied('interrupted',3),p=spawnSync(process.execPath,[join(A.E.H,'worker.mjs'),'publish',s,run.history[4],'before-switch'],{encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024});assert.equal(p.status,91,p.stderr);assert.equal(A.current(s).generation,run.history[3]);const view=spawnSync(process.execPath,[join(A.E.H,'worker.mjs'),'view',s,run.history[4]],{encoding:'utf8',timeout:30000});assert.equal(view.status,0,view.stderr);assert.equal(JSON.parse(view.stdout).unpublishedRejected,true);A.recover(s);await A.publish(s,run.history[4]);assert.equal(A.current(s).generation,run.history[4]);});

test('a superseded regional result is stale under current policy, valid under fixed exact inputs',async()=>{const p=await A.D.pin(store,run.history[4]),id='dtm-cluster-0-0|slope',old=values[0].riffelhornDerived.active[id],st=values[4].riffelhornDerived;assert.notEqual(st.active[id],old);const historical=p.result('riffelhorn',id,old);assert.equal(historical.status,'historical');assert.equal(historical.assessment.status,'fresh');const current=A.M.assess(values[4].riffelhornDependencyState,{...st,active:{[id]:old}});assert.equal(current[old].status,'stale');assert.deepEqual(historical.result.value,values[0].riffelhornDerived.results[old].value);});
test('broken source/provenance identities reject rather than inventing observations',()=>{assert.throws(badLedger(l=>l.records.find(r=>r.assignment==='exe:2024-03:point').lineage.source.sha256='0'.repeat(64)),/identity/);assert.throws(badLedger(l=>l.records.find(r=>r.assignment.startsWith('riffelhorn:dtm:')).physical.extent={kind:'instant',value:'2024-01-01T00:00:00Z',precision:'second',basis:'unjustified edition inference'}),/identity/);});

test('independent closure equals every stale and changed regional identity, not only counts',()=>{const before=values[0].riffelhornDependencyState,after=values[2].riffelhornDependencyState,old=values[0].riffelhornDerived,st=values[2].riffelhornDerived;const expected=A.M.expectedAffected(before,after,old),stale=Object.values(A.M.assess(after,old)).filter(r=>r.status==='stale').map(r=>r.id).sort(),changed=Object.keys(old.active).filter(id=>old.active[id]!==st.active[id]).sort();assert.deepEqual(stale,expected);assert.deepEqual(changed,expected);assert.equal(expected.length,8);assert.deepEqual(run.updates.find(u=>u.stage===2).runs[0].regional.expected,expected);});

test('instant at interval start matches source support, next interval does not',()=>{const ledger=values[4].temporalKnowledge,q={feature:'rfo:31383',physical:{start:'2014-02-04T00:00:00Z',end:'2014-02-04T00:00:00Z',role:'event'}};assert.equal(A.T.query(ledger,q).matches.length,1);q.physical.start=q.physical.end='2014-02-06T00:00:00Z';assert.equal(A.T.query(ledger,q).matches.length,0);});

test('unknown-time selection still applies other temporal predicates',()=>{const l=values[4].temporalKnowledge,q={assignment:'exe:wfd',unknown:'physical',sourcePeriod:['2025-06-23','2025-06-23']};assert.equal(A.T.query(l,q).matches.length,1);assert.equal(A.T.query(l,{...q,sourcePeriod:['2020','2020']}).matches.length,0);});
test('adjacent reversed query days reject rather than forming an empty interval',()=>{const l=values[4].temporalKnowledge;assert.throws(()=>A.T.query(l,{physical:{start:'2024-03-02',end:'2024-03-01',role:'observation'}}),/ordering/);assert.throws(()=>A.T.query(l,{sourcePeriod:['2024-03-02','2024-03-01']}),/ordering/);});

test('impossible calendar dates reject even with a seconds-precision timestamp',()=>{const l=values[4].temporalKnowledge,value='2024-02-30T00:00:00Z';assert.throws(()=>A.T.timeBounds({kind:'instant',value,precision:'second',basis:'negative contract fixture'}),/calendar/);assert.throws(()=>A.T.query(l,{sourcePeriod:[value,value]}),/calendar/);});
