// Isolated browser consumer. Fetches only the versioned serving boundary.
const $=id=>document.getElementById(id),map=$('map'),ctx=map.getContext('2d');
const views={full:[264900,357800,267900,360800],summit:[266205,359187,266605,359587],southern:[265676.05347833806,358139.7631202109,266076.05347833806,358539.7631202109],north:[266200,360250,266600,360650]};
let scene=null,bounds=[...views.full],marker=null,latest=null,drag=null,moved=false,sequence=0,refreshSequence=0;
async function json(url,request){const r=await fetch(url,request?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)}:{});const v=await r.json();if(!r.ok && v.error)throw new Error(v.error.code);return v;}
async function image(url){const r=await fetch(url);if(!r.ok)throw new Error('Image unavailable');return createImageBitmap(await r.blob());}
function frame(){const scale=Math.min(960/(bounds[2]-bounds[0]),720/(bounds[3]-bounds[1]));return {scale,x:(960-(bounds[2]-bounds[0])*scale)/2,y:(720-(bounds[3]-bounds[1])*scale)/2};}
function xy(p){const f=frame();return [f.x+(p[0]-bounds[0])*f.scale,f.y+(bounds[3]-p[1])*f.scale];}
function point(event){const r=map.getBoundingClientRect(),f=frame(),x=(event.clientX-r.left)/r.width*960,y=(event.clientY-r.top)/r.height*720;return [bounds[0]+(x-f.x)/f.scale,bounds[3]-(y-f.y)/f.scale];}
function draw(){if(!scene)return;ctx.fillStyle='#26343b';ctx.fillRect(0,0,960,720);ctx.imageSmoothingEnabled=false;ctx.save();const f=frame();ctx.beginPath();ctx.rect(f.x,f.y,(bounds[2]-bounds[0])*f.scale,(bounds[3]-bounds[1])*f.scale);ctx.clip();
 const b=scene.manifest.layers.appearance.bounds,a=xy([b[0],b[3]]),z=xy([b[2],b[1]]);if($('appearance').checked)ctx.drawImage(scene.appearance,...a,z[0]-a[0],z[1]-a[1]);
 if($('nrw').checked){ctx.strokeStyle='#f6e9af';ctx.lineWidth=1;for(const f of scene.nrw.features){const g=f.properties.nativeSupport.geometry;const polys=g.type==='Polygon'?[g.coordinates]:g.coordinates;for(const poly of polys){ctx.beginPath();for(const ring of poly){ring.forEach((p,i)=>{const [x,y]=xy(p);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.closePath();}ctx.stroke();}}}
 if(marker){const [x,y]=xy(marker);ctx.strokeStyle='#00ffff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.stroke();}
 ctx.restore();ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(10,10,540,45);ctx.fillStyle='white';ctx.font='13px system-ui';ctx.fillText('Retained Lab010 · 2026-07-12 · BNG map plane · historical NRW',18,29);ctx.fillText('Generation '+scene.generation.slice(0,16)+' · no appearance correction',18,47);
}
async function refresh(){const refreshTicket=++refreshSequence;const current=await json('/pilot/v1/current'),root='/pilot/v1/g/'+current.generation,manifest=await json(root+'/manifest');const asset=f=>manifest.assets.find(a=>a.family===f);
 const [appearance,wc,nrw,rights]=await Promise.all([image(asset('appearance').url),image(asset('worldcover').url),manifest.layers.nrw.applicability==='withheld'?Promise.resolve({features:[]}):json(asset('nrw').url),Promise.all(manifest.families.map(f=>json(f.rightsURL)))]);
 if(refreshTicket!==refreshSequence){appearance.close();wc.close();return;}sequence++;
 const next={generation:current.generation,root,manifest,appearance,wc,nrw};const old=scene;scene=next;old?.appearance.close();old?.wc.close();latest=null;marker=null;$('summary').textContent='Select a place for independent qualified answers.';
 $('generation').textContent='Pinned generation '+scene.generation;$('answer').textContent='Select a place.';$('provenance').textContent='';$('status').textContent=manifest.layers.nrw.applicability==='withheld'?'Scene pinned; controlled NRW applicability withheld, not physical absence.':'Scene pinned; publication changes require explicit refresh.';
 $('nrw').disabled=manifest.layers.nrw.applicability==='withheld';
 $('rights').replaceChildren(...rights.map(r=>{const p=document.createElement('p');const list=Array.isArray(r.rights)?r.rights:[r.rights];const texts=[...new Set(list.map(v=>typeof v==='object'?(v.attribution??'Attribution detail unknown')+'; '+(v.licence?.value??v.licence?.status??v.data_terms??'source rights remain qualified'):String(v)))];p.textContent=r.family+' · '+texts.join(' | ');return p;}));
 $('legend').replaceChildren(...Object.entries(manifest.layers.worldcover.palette).filter(([c])=>c!=='0').map(([c,rgb])=>{const span=document.createElement('span'),swatch=document.createElement('i');swatch.className='swatch';swatch.style.background=`rgb(${rgb.slice(0,3).join(',')})`;span.append(swatch,c);return span;}));
 $('wc').getContext('2d').drawImage(wc,0,0);$('cell').textContent='2021 nominal classification; native assignments. No selected cell in the new scene.';$('terrain').getContext('2d').clearRect(0,0,256,256);$('tile').textContent='No selected terrain tile in the new scene.';draw();
}
function find(value,predicate){if(!value || typeof value!=='object')return null;if(predicate(value))return value;for(const child of Object.values(value)){const found=find(child,predicate);if(found)return found;}return null;}
async function query(p){const pinned=scene,ticket=++sequence;if(!pinned)return;marker=p;draw();$('status').textContent='Querying pinned evidence…';
 const result=await json(pinned.root+'/query',{property:'place-evidence',place:{crs:'EPSG:27700',point:p}});if(scene!==pinned || ticket!==sequence)return;
 if(result.generation!==pinned.generation)throw new Error('Generation mismatch');latest=result;const rows=result.answers.map(a=>{const r=a.response,record=r.answers?.[0]?.records?.[0],derived=r.answers?.[0]?.result?.claim?.result?.value?.value;let text=a.property+' · ';if(derived!==undefined)text+=derived.toFixed(3)+(a.property==='derived-slope'?' degrees':' dimensionless')+' · '+r.freshness.status;else if(record?.cell)text+='native code '+record.cell.code+' · 2021 classification';else if(record?.feature)text+='native feature '+record.feature.id+' · '+record.claim.native.fields.phase1_code+' · historical survey time unknown';else if(a.property==='appearance')text+='12 July 2026 source/prepared observation; no physical recovery';else text+=r.status==='excluded-by-context'?'excluded by controlled applicability; inventory remains registered':record?.operationalStatus==='unavailable'?'unavailable':r.result?.reason??'qualified retained selection';const p=document.createElement('p');p.textContent=text;return p;});$('summary').replaceChildren(...rows);$('answer').textContent=JSON.stringify(result,null,2);
 const cell=find(result,r=>r.family==='worldcover' && r.cell);const wc=$('wc').getContext('2d');wc.drawImage(pinned.wc,0,0);if(cell){wc.strokeStyle='#ff00ff';wc.lineWidth=2;wc.strokeRect(cell.cell.column-3,cell.cell.row-3,7,7);$('cell').textContent=`Native row ${cell.cell.row}, column ${cell.cell.column}, code ${cell.cell.code} · 2021; whole-cell class, not cover fraction.`;}else $('cell').textContent='No native cell returned for this qualified query; no absence inferred.';
 const delivery=find(result,r=>r.delivery)?.delivery,t=$('terrain').getContext('2d');t.clearRect(0,0,256,256);
 if(delivery?.url){const im=await image(delivery.url);if(scene!==pinned || ticket!==sequence){im.close();return;}t.drawImage(im,0,0);im.close();const pixel=delivery.probe.xyz.pixel;t.strokeStyle='#00ffff';t.strokeRect(pixel[0]-4,pixel[1]-4,8,8);$('tile').textContent=delivery.family+' · exact z'+delivery.probe.xyz.z+' tile; marker from service; delivery is not physical resolution. '+(find(result,r=>r.roots?.[0]?.encoding)?.roots[0].encoding??'Height datum/epoch remain qualified.');}else $('tile').textContent='No retained terrain derivation/tile selected for this point. Only two frozen probes supported.';
 $('status').textContent=result.result?.reason??'Independent qualified evidence returned; no canonical cover selected.';
}
function failure(e){$('status').textContent='Explicit unavailable/error: '+e.message;}
$('refresh').onclick=()=>refresh().catch(failure);$('summit').onclick=()=>query([266405,359387]).catch(failure);$('view').onchange=()=>{bounds=[...views[$('view').value]];draw();};for(const id of ['appearance','nrw'])$(id).onchange=draw;
$('trace').onclick=async()=>{if(!latest)return;const pinned=scene;try{const p=await json(latest.provenanceURL);if(scene===pinned)$('provenance').textContent=JSON.stringify(p,null,2);}catch(e){failure(e);}};
map.onpointerdown=e=>{drag={point:point(e),bounds:[...bounds]};moved=false;map.setPointerCapture(e.pointerId);};
map.onpointermove=e=>{if(!drag)return;const p=point(e),dx=p[0]-drag.point[0],dy=p[1]-drag.point[1];if(Math.abs(dx)+Math.abs(dy)>2)moved=true;bounds=[drag.bounds[0]-dx,drag.bounds[1]-dy,drag.bounds[2]-dx,drag.bounds[3]-dy];drag.point=point(e);drag.bounds=[...bounds];draw();};
map.onpointerup=e=>{drag=null;if(!moved)query(point(e)).catch(failure);};map.onwheel=e=>{e.preventDefault();const p=point(e),factor=e.deltaY>0?1.15:1/1.15;bounds=[p[0]+(bounds[0]-p[0])*factor,p[1]+(bounds[1]-p[1])*factor,p[0]+(bounds[2]-p[0])*factor,p[1]+(bounds[3]-p[1])*factor];draw();};
refresh().catch(failure);
