import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import {join} from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {createInterface} from 'node:readline';
import * as I from './integration.mjs';import {encode,sha} from '../../../pilots/atlas/tryfan/identity.mjs';
const matrix=JSON.parse(fs.readFileSync(new URL('./matrix.json',import.meta.url),'utf8'));let store,seed,history=[],values=[],members=[];
const requests=matrix.cases.slice(0,1).concat(matrix.cases.slice(9,10)).map(({region,query})=>({region,query}));
function clean(a){const v=structuredClone(a);for(const x of v.answers)delete x.metrics;return v;}
function clone(name){const s=join(I.plan.stateRoot,'negative-'+name+'-'+Date.now());fs.cpSync(store,s,{recursive:true});I.owned(s);return s;}
function invalidPublication(s,change){const p=structuredClone(I.resolveGeneration(s,history.at(-1)).publication);p.ordinal=4;p.predecessor=history.at(-1);change(p);const b=encode(p),g=sha(b);const file=join(s,'publications',g+'.json');if(fs.existsSync(file))assert.equal(fs.readFileSync(file,'utf8'),b);else fs.writeFileSync(file,b,{flag:'wx'});return g;}
before(async()=>{store=join(I.plan.stateRoot,'tests-'+Date.now());seed=await I.seed(store);let value=seed.value;for(let n=0;n<3;n++){if(n)value=I.revise(value,n===1?'riffelhorn':'tryfan');values.push(value);const g=I.prepare(store,value,seed.locators,{ordinal:n+1,predecessor:history.at(-1)??null});await I.publish(store,g);history.push(g);members.push(I.resolveGeneration(store,g).publication.members);}});
test('explicit two-region registration preserves real populations',()=>{assert.equal(values[0].riffelhornRegistration.records.length,44);assert.equal(values[0].riffelhornRegistration.inputs.length,12);assert.equal(values[0].riffelhornRegistration.semanticDeclarations,50);assert.equal(values[0].catalogue.artifacts.length,310);assert.equal(values[0].understanding.results.length,6);});
test('one registration component changes per independent administrative update',()=>{assert.deepEqual(Object.keys(members[0]).filter(k=>members[0][k]!==members[1][k]),['riffelhornRegistration']);assert.deepEqual(Object.keys(members[1]).filter(k=>members[1][k]!==members[2][k]),['tryfanRegistration']);});
test('native Tryfan components remain byte-identical to accepted reference',()=>{for(const key of ['catalogue','knowledge','understanding','serving'])assert.equal(encode(values[2][key]),encode(seed.value[key]));});
test('supports retain disconnected native coordinate references',()=>{assert.equal(values[0].tryfanRegistration.support.crs,'EPSG:27700');assert.equal(values[0].riffelhornRegistration.support.crs,'EPSG:2056');assert.equal(values[0].riffelhornRegistration.support.areaKm2,4);});
test('current/recent/old membership has no ancestry traversal',async()=>{for(const g of history){const r=await I.measured(()=>I.resolveGeneration(store,g,{hydrate:true}));assert.equal(r.measurement.counters.ancestryTraversals,0);assert.equal(r.measurement.counters.membershipVisits,33);assert.equal(r.measurement.counters.componentEdges,7);assert.equal(r.value.generation,g);}});
test('full current validation verifies both real byte populations',()=>{assert.equal(I.plan.regions.riffelhorn.preparedRevision,values[0].riffelhornRegistration.preparationRevision);assert.equal(values[0].riffelhornRegistration.inputs.reduce((n,a)=>n+a.bytes,0),120347916);});
test('old and new pins retain distinct registration contexts with equal native evidence',async()=>{const a=await I.pin(store,history[0]),b=await I.pin(store,history[2]);try{const x=await a.query(requests),y=await b.query(requests);for(let n=0;n<2;n++){assert.notEqual(x.answers[n].registrationIdentity,y.answers[n].registrationIdentity);assert.deepEqual(n===0?I.normalizeTryfan(x.answers[n].native,a.generation):x.answers[n].native,n===0?I.normalizeTryfan(y.answers[n].native,b.generation):y.answers[n].native);}}finally{await a.close();await b.close();}});
test('unpublished complete candidate cannot be pinned or current',async()=>{const g=I.prepare(store,values[2],seed.locators,{ordinal:4,predecessor:history[2]});assert.equal(I.current(store).generation,history[2]);await assert.rejects(I.pin(store,g),/Unknown|pre-switch/);});
test('invalid registration fails before immutable preparation',()=>{const v=structuredClone(values[2]);v.riffelhornRegistration.preparationRevision='0'.repeat(64);assert.throws(()=>I.prepare(store,v,seed.locators,{ordinal:4,predecessor:history[2]}),/Region identity/);assert.equal(I.current(store).generation,history[2]);});
test('invalid cross-region support is not silently converted',()=>{const v=structuredClone(values[2]);v.riffelhornRegistration.support=v.tryfanRegistration.support;assert.throws(()=>I.prepare(store,v,seed.locators,{ordinal:4,predecessor:history[2]}),/Region identity/);});
test('missing component rejects publication and leaves root unchanged',async()=>{const s=clone('missing'),g=invalidPublication(s,p=>p.members.riffelhornRegistration='0'.repeat(64));await assert.rejects(I.publish(s,g),/unavailable/);assert.equal(I.current(s).generation,history[2]);});
test('incomplete closure rejects attempted root advance',async()=>{const s=clone('incomplete'),g=invalidPublication(s,p=>delete p.members.tryfanRegistration);await assert.rejects(I.publish(s,g),/Exact explicit membership/);assert.equal(I.current(s).generation,history[2]);});
test('swapped regional component kind rejects publication',async()=>{const s=clone('cross'),g=invalidPublication(s,p=>p.members.riffelhornRegistration=p.members.tryfanRegistration);await assert.rejects(I.publish(s,g),/Wrong component kind/);assert.equal(I.current(s).generation,history[2]);});
test('malformed registration metadata cannot replace exact source closure',()=>{const v=structuredClone(values[2]);delete v.riffelhornRegistration.inputs;assert.throws(()=>I.prepare(store,v,seed.locators,{ordinal:4,predecessor:history[2]}),/Invalid record fields/);});
test('missing prepared fixture fails explicitly in isolated locator',()=>{const s=join(I.plan.stateRoot,'empty-prepared-'+Date.now());fs.mkdirSync(s);assert.throws(()=>I.python(['--verify','--root',s]),/Missing|complete|manifest|absent/i);});
test('mismatched prepared bytes fail without changing retained originals',()=>{const s=join(I.plan.stateRoot,'bad-prepared-'+Date.now());fs.mkdirSync(s);const data=join(I.PYTHON,'../../../..');const original=join(data,I.plan.regions.riffelhorn.rootRelative);for(const f of fs.readdirSync(original))fs.copyFileSync(join(original,f),join(s,f));fs.appendFileSync(join(s,'features.json'),' ');assert.throws(()=>I.python(['--verify','--root',s]),/hash|corrupt|identity|member/i);});
for(const point of ['after-components','before-switch'])test('process interruption '+point+' preserves root and recovery retry',async()=>{const s=clone(point),g=I.prepare(s,values[2],seed.locators,{ordinal:4,predecessor:history[2]});const p=spawnSync(process.execPath,[join(I.H,'worker.mjs'),'publish',s,g,point],{encoding:'utf8',timeout:60000});assert.equal(p.status,91,p.stderr);assert.equal(I.current(s).generation,history[2]);const restart=spawnSync(process.execPath,[join(I.H,'worker.mjs'),'recover-view',s,g],{encoding:'utf8',timeout:60000,maxBuffer:4*1024*1024});assert.equal(restart.status,0,restart.stderr);assert.equal(JSON.parse(restart.stdout).generation,history[2]);assert.equal(JSON.parse(restart.stdout).unpublishedRejected,true);const old=await I.pin(s,history[0]);try{assert.equal((await old.query(requests)).generation,history[0]);}finally{await old.close();}I.recover(s);await I.publish(s,g);assert.equal(I.current(s).generation,g);});
test('missing historical-only component fails old pin while current survives',async()=>{const s=clone('historical');const file=join(s,'components',members[0].riffelhornRegistration+'.json');assert.notEqual(members[0].riffelhornRegistration,members[2].riffelhornRegistration);fs.unlinkSync(file);await assert.rejects(I.pin(s,history[0]),/unavailable/);assert.equal((await I.pin(s,history[2])).generation,history[2]);});
test('unknown region never falls back to different support',async()=>{const p=await I.pin(store);try{await assert.rejects(p.query([{region:'unknown',query:{}}]),/Unknown support/);}finally{await p.close();}});
test('fresh process independently replays three historical contexts',()=>{const fixture=join(store,'replay.json');fs.writeFileSync(fixture,encode({history}));const r=spawnSync(process.execPath,[join(I.H,'worker.mjs'),'replay',store,fixture],{encoding:'utf8',timeout:120000,maxBuffer:4*1024*1024});assert.equal(r.status,0,r.stderr);assert.equal(Object.keys(JSON.parse(r.stdout).answers).length,3);});
function consumer(s,g){const c=spawn(process.execPath,[join(I.H,'worker.mjs'),'consumer',s,...(g?[g]:[])],{stdio:['pipe','pipe','pipe']});let pending=[],readyResolve,readyReject;const ready=new Promise((r,j)=>{readyResolve=r;readyReject=j;});let err='';c.stderr.on('data',d=>err+=d);createInterface({input:c.stdout}).on('line',line=>{const v=JSON.parse(line);if(v.ready)readyResolve(v);else{const p=pending.shift();if(v.error)p.reject(Error(v.error.message));else p.resolve(v.value);}});c.on('error',readyReject);c.on('exit',code=>{if(code){readyReject(Error(err));for(const p of pending)p.reject(Error(err));}});return {ready,query:requests=>new Promise((resolve,reject)=>{pending.push({resolve,reject});c.stdin.write(JSON.stringify({requests})+'\n');}),close:()=>c.exitCode!==null?Promise.resolve():new Promise(resolve=>{c.on('exit',resolve);c.stdin.end();})};}
test('isolated consumer remains pinned before during and after composite switch',async()=>{const s=join(I.plan.stateRoot,'consumer-'+Date.now()),base=await I.seed(s),g1=I.prepare(s,base.value,base.locators,{ordinal:1});await I.publish(s,g1);const old=consumer(s);await old.ready;let newer;try{const before=await old.query(requests),v=I.revise(base.value,'riffelhorn'),g2=I.prepare(s,v,base.locators,{ordinal:2,predecessor:g1});assert.deepEqual(clean(await old.query(requests)),clean(before));assert.equal(I.current(s).generation,g1);await I.publish(s,g2);assert.deepEqual(clean(await old.query(requests)),clean(before));newer=consumer(s);const pin=await newer.ready;assert.equal(pin.generation,g2);const q=await newer.query(requests);assert.equal(q.answers[1].registration.revision,1);assert.equal(q.answers[0].registration.revision,0);assert.ok(q.answers.every(a=>a.generation===g2));}finally{await old.close();if(newer)await newer.close();}});

test('selected publications do not traverse unavailable predecessor publication',async()=>{const s=clone('no-ancestor');fs.unlinkSync(join(s,'publications',history[1]+'.json'));for(const g of [history[0],history[2]]){const p=await I.pin(s,g);try{assert.equal((await p.query(requests)).generation,g);}finally{await p.close();}}});

test('tampered selected component blocks querying and publication',async()=>{const s=clone('tampered'),file=join(s,'components',members[2].riffelhornRegistration+'.json'),g=invalidPublication(s,p=>p.ordinal=4);fs.appendFileSync(file,' ');await assert.rejects(I.pin(s,history[2]),/Immutable proof bytes changed/);await assert.rejects(I.publish(s,g),/Immutable proof bytes changed/);assert.equal(I.current(s).generation,history[2]);});
