"""Bounded empty-state reproduction and fresh-process observations, not a benchmark framework."""
from pathlib import Path
import json,statistics,subprocess,sys,tempfile,time,tracemalloc
import prepare as p
D=p.resolve_storage_roots(repository_root=p.R,require_data=True).data
scratch=Path(tempfile.mkdtemp(prefix='riffelhorn-reproduction-'))
runs=[p.prepare(D,scratch/str(n)) for n in range(3)]
final=p.prepare(D,D/'derived/atlas/riffelhorn/riffelhorn-qualified-fixture-v1')
root=Path(final['preparedRoot']);verified=[]
for n in range(3):
 start=time.perf_counter();q=subprocess.run([sys.executable,str(p.H/'prepare.py'),'verify','--output',str(root)],cwd=p.R,capture_output=True,text=True,encoding='utf-8');p.require(q.returncode==0,q.stderr);verified.append({**json.loads(q.stdout),'processElapsedSeconds':time.perf_counter()-start})
identical=all((Path(a['preparedRoot'])/f).read_bytes()==(root/f).read_bytes() for a in runs for f in [*p.FILES,'manifest.json']);p.require(identical,'reproduction mismatch')
tracemalloc.start();outputs=p.build(D);_,peak=tracemalloc.get_traced_memory();tracemalloc.stop()
summary=lambda xs:{'median':statistics.median(xs),'min':min(xs),'max':max(xs),'runs':len(xs)}
result={'schema':'atlas-riffelhorn-preparation-observations/v1','startingCheckpoint':p.load(p.PLAN)['startingCheckpoint'],'planSha256':p.sha(p.PLAN),'tools':p.tools(),'revision':final['revision'],'externalRootRelative':str(root.relative_to(D)).replace(chr(92),'/'),'manifest':p.load(root/'manifest.json'),'byteIdenticalEmptyRebuilds':identical,'independentEmptyRuns':runs,'retainedPreparation':final,'freshProcessRuns':verified,'preparationSeconds':summary([a['timingSeconds']['total'] for a in runs]),'buildSeconds':summary([a['timingSeconds']['build'] for a in runs]),'freshProcessVerificationSeconds':summary([a['verificationSeconds'] for a in verified]),'freshProcessWallSeconds':summary([a['processElapsedSeconds'] for a in verified]),'pythonBuildPeakTrackedBytes':peak,'memoryLimit':'tracemalloc Python allocation peak for one separate build, excludes native GDAL/Fiona/PROJ and Node child RSS; not whole-process peak','inputBytes':sum(a['bytes'] for a in p.load(p.SPEC)['inputs']),'outputBytes':final['outputBytes'],'storageAmplificationAdditional':final['outputBytes']/sum(a['bytes'] for a in p.load(p.SPEC)['inputs']),'rasterPayloadCopies':0,'nativeFeatures':len(outputs['features.json']['features']),'semanticCounts':{k:len(outputs['semantic-evidence.json'][k]) for k in ['resources','definitions','mappings','collections']},'claims':sum(len(c['claims']) for c in outputs['semantic-evidence.json']['collections']),'byteCounters':'Each build hashes120347916input bytes and reads native headers, existing JSON, ZIP selection and68016WorldCoveruint8samples. First preparation+verification performs two builds. Physical cache/GDAL/archive I/O not instrumented. Encoding writes five artifacts plus completion manifest; verification rereads artifact hashes. Retry additionally reconstructs prior complete revision and retains staging metadata.','sourceImplementationHashes':{str(f.relative_to(p.R)).replace(chr(92),'/'):p.sha(f) for f in [p.H/'prepare.py',p.H/'verify_semantic.mjs']},'integrationReady':'prepared qualified native records and bindings only; no world-model registration/query/publication/consumer integration','decision':'C - PROOF SUCCESS'}
result['nextTask']=p.load(p.H/'next-task.json')
result['semanticValidatorTools']={'node':subprocess.check_output(['node','--version'],text=True).strip(),'vite':p.load(p.R/'node_modules/vite/package.json')['version']}
(p.R/'docs/research/atlas-riffelhorn-preparation-results.json').write_bytes(p.canonical(result));print(json.dumps({k:result[k] for k in ['revision','outputBytes','claims','preparationSeconds','freshProcessVerificationSeconds','pythonBuildPeakTrackedBytes','byteIdenticalEmptyRebuilds']}))
