import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync,readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join,resolve,sep } from 'node:path';
import { spawn,spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline';
import { load,STORE,currentId,register,stage } from '../generations.mjs';
import { DATA,verifyArtifacts } from '../catalogue.mjs';
import { openWorld } from '../world.mjs';
import { openEvidence,NativeSession } from '../query.mjs';
import { encode,sha } from '../identity.mjs';
import { buildDelivery,openDelivery } from '../delivery.mjs';
let dir,store,server,url,g1,g2,world,a,b,initial;
const summit=[266405,359387],request=property=>({property,place:{crs:'EPSG:27700',point:summit}});
function processLines(file,args) {
 const child=spawn(process.execPath,[file,...args],{stdio:['pipe','pipe','pipe']}),queue=[];let stderr='';child.stderr.on('data',v=>stderr+=v);
 const lines=[];createInterface({input:child.stdout}).on('line',l=>{if(queue.length)queue.shift()(l);else lines.push(l);});
 const next=()=>lines.length?Promise.resolve(lines.shift()):new Promise((r,j)=>{const timer=setTimeout(()=>j(new Error('Process timeout '+stderr)),30000);queue.push(l=>{clearTimeout(timer);r(l);});});
 return {child,next,call:async r=>{child.stdin.write(JSON.stringify(r)+'\n');return JSON.parse(await next());},stderr:()=>stderr};
}
function cloneStore(target) {
 for(const folder of ['generations','locators','artifacts'])mkdirSync(join(target,folder),{recursive:true});
 let s=load(STORE,{verify:false});while(s.value.update)s=load(STORE,{generation:s.value.parent,verify:false});const selected=s.generation;for(;;){writeFileSync(join(target,'generations',s.generation+'.json'),encode(s.value));writeFileSync(join(target,'locators',s.generation+'.json'),encode(s.locators));if(!s.value.parent)break;s=load(STORE,{generation:s.value.parent,verify:false});}
 writeFileSync(join(target,'current.json'),encode({format:'atlas-tryfan-pilot-store/v1',generation:selected}));
 for(const file of readdirSync(join(STORE,'artifacts')))writeFileSync(join(target,'artifacts',file),readFileSync(join(STORE,'artifacts',file)));
}
async function http(path,body){const r=await fetch(url+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,value:await r.json(),headers:r.headers};}
const query=(g,p)=>http('/pilot/v1/g/'+g+'/query',p),route=(g,p)=>'/pilot/v1/g/'+g+'/'+p;
async function start(target){const p=processLines(resolve(import.meta.dirname,'../server.mjs'),['--port','0','--store',target]);let text=await p.next();while(!text.includes('url'))text=await p.next();const address=text.match(/http:\/\/127\.0\.0\.1:\d+/)[0];return {p,address};}
before(async()=>{dir=mkdtempSync(join(tmpdir(),'meridian-s4-'));store=join(dir,'store');cloneStore(store);initial=load(store);g1=initial.generation;({p:server,address:url}=await start(store));world=await openWorld({store,generation:g1});});
after(async()=>{a?.child.stdin.end();b?.child.stdin.end();server?.child.kill();await world?.close();assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));rmSync(dir,{recursive:true,force:true});});
test('H01 explicit current generation and no-store bootstrap',async()=>{const r=await http('/pilot/v1/current');assert.equal(r.status,200);assert.equal(r.value.generation,g1);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.value.capabilities.serving,true);});
test('H02 WorldCover native30 and400m counts through pinned HTTP',async()=>{const r=await query(g1,request('worldcover-native'));assert.equal(r.value.answers[0].records[0].cell.code,30);const s=await query(g1,{property:'worldcover-support',place:{crs:'EPSG:27700',bounds:[266205,359187,266605,359587]},time:'2021'});assert.deepEqual(s.value.answers[0].records[0].assignments.counts,{'10':29,'30':3039,'60':28});});
test('H03 NRW native486832 inventory identity and mapping loss',async()=>{const r=await query(g1,request('nrw-native')),v=r.value.answers[0].records[0];assert.equal(v.feature.id,'486832');assert.equal(v.claim.native.fields.phase1_code,'D.1.1');assert.ok(JSON.stringify(v).includes('loss'));assert.ok(JSON.stringify(v).includes('unknown'));});
test('H04 coexistence has both native families; no winner',async()=>{const r=await query(g1,request('coexisting-semantic'));assert.deepEqual([...new Set(r.value.answers[0].records.map(r=>r.family))],['worldcover','nrw']);});
test('H05 retained slope/ratio and freshness/method survive serving',async()=>{const s=await query(g1,request('derived-slope')),a=await query(g1,request('derived-area-ratio'));assert.equal(s.value.answers[0].result.claim.result.value.value,11.837956999552308);assert.equal(a.value.answers[0].result.claim.result.value.value,1.0217304696061646);assert.equal(s.value.freshness.status,'fresh');assert.ok(s.value.answers[0].result.receipt.methodRevision);});
test('H06-H07 deterministic generation, CLI/HTTP semantic equality',async()=>{const r=await query(g1,request('nrw-native')),again=await query(g1,request('nrw-native'));assert.deepEqual(r.value,again.value);const native=await world.query(request('nrw-native'));const projection=await openDelivery({store});try{assert.deepEqual(r.value.answers,projection.project(native,g1).answers);}finally{await projection.close();}assert.equal(r.value.generation,g1);});
test('H08-H11 actual separate writer publication between active reader queries',async()=>{a=processLines(resolve(import.meta.dirname,'../client/session-consumer.mjs'),[url]);assert.equal((await a.call({operation:'pin'})).generation,g1);assert.equal((await a.call({query:request('place-evidence')})).generation,g1);
 const writer=spawnSync(process.execPath,[resolve(import.meta.dirname,'http-worker.mjs'),store],{encoding:'utf8',timeout:30000});assert.equal(writer.status,0,writer.stderr);g2=JSON.parse(writer.stdout).generation;assert.notEqual(g2,g1);assert.equal(currentId(store),g2);
 const old=await a.call({query:request('place-evidence')});assert.equal(old.generation,g1);assert.ok(old.value.answers.every(v=>v.response.generation===g1));
 b=processLines(resolve(import.meta.dirname,'../client/session-consumer.mjs'),[url]);assert.equal((await b.call({operation:'pin'})).generation,g2);const newer=await b.call({query:request('place-evidence')});assert.ok(newer.value.answers.every(v=>v.response.generation===g2));assert.equal((await a.call({operation:'pin'})).error,'invalid-context-transition');});
test('H12 explicit historical generation never upgrades',async()=>{const r=await query(g1,request('derived-slope'));assert.equal(r.value.generation,g1);assert.equal((await http('/pilot/v1/current')).value.generation,g2);});
test('H13 unknown and staged/unpublished generation404',async()=>{assert.equal((await query('f'.repeat(64),request('nrw-native'))).status,404);const s=load(store);const staged=stage(store,{...s.value,parent:s.generation},s.locators);assert.equal((await query(staged.generation,request('nrw-native'))).status,404);});
test('H14 unsupported/current/property fallback remains qualified200',async()=>{for(const property of ['current-cover','physical-appearance','not-a-property']){const r=await query(g1,request(property));assert.equal(r.status,200);assert.equal(r.value.result.reason,'unsupported');}const r=await query(g1,{...request('nrw-native'),evidence:'terrain'});assert.equal(r.value.status,'excluded-by-context');});
test('H15 missing registered WC503/qualified unavailable differs from native nodata',async()=>{const isolated=join(dir,'missing');cloneStore(isolated);const map=JSON.parse(readFileSync(join(isolated,'locators',g1+'.json')));const asset=initial.value.catalogue.artifacts.find(a=>a.uses.some(u=>u.family==='worldcover'));map[asset.id]='operational-fixture-missing';writeFileSync(join(isolated,'locators',g1+'.json'),encode(map));const s=await start(isolated);try{const r=await fetch(s.address+route(g1,'query'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request('worldcover-native'))});const v=await r.json();assert.equal(r.status,503);assert.equal(v.status,'unavailable');assert.equal(v.answers[0].records[0].reason,'artifact-unavailable');assert.ok(!JSON.stringify(v).includes('not-classified'));}finally{s.p.child.kill();}});
test('H16 method-relative stale remains retained and no recomputation',async()=>{const r=await query(g1,{...request('derived-slope'),methodRevision:'prospective-policy-revision-not-implemented'});assert.equal(r.status,200);assert.equal(r.value.freshness.status,'stale');assert.equal(r.value.answers[0].status,'stale');assert.equal(r.value.answers[0].result.claim.result.value.value,11.837956999552308);assert.equal(currentId(store),g2);});
test('H17-H18 genuinely fresh serving and boundary-only consumer reproduce',async()=>{const s=await start(store);try{const c=spawnSync(process.execPath,[resolve(import.meta.dirname,'../client/http-consumer.mjs'),s.address,g1],{encoding:'utf8',timeout:30000,maxBuffer:4*1024*1024});assert.equal(c.status,0,c.stderr);const v=JSON.parse(c.stdout);assert.equal(v.generation,g1);assert.equal(v.answer.answers.length,6);assert.equal(v.assetBytes,148616);}finally{s.p.child.kill();}});
test('H19-H20 exact terrain bytes, ETag and explicit missingz13',async()=>{const manifest=(await http(route(g1,'manifest'))).value;assert.equal(manifest.terrain.length,298);const tile=manifest.terrain.find(t=>t.family==='terrain-common'&&t.tile.z===14);const r=await fetch(url+tile.url),body=Buffer.from(await r.arrayBuffer());assert.equal(sha(body),tile.sha256);assert.equal(r.headers.get('x-atlas-generation'),g1);assert.equal((await fetch(url+tile.url,{headers:{'If-None-Match':r.headers.get('etag')}})).status,304);assert.equal((await http(route(g1,'terrain/terrain-common/13/4005/2664.png'))).status,503);});
test('H21 durable provenance/rights route, no internal filenames in consumer',async()=>{const q=(await query(g1,request('derived-slope'))).value,p=(await http(q.provenanceURL)).value;assert.equal(p.generation,g1);assert.equal(p.derived.length,4);assert.equal(p.sources.length,5);const m=(await http(route(g1,'manifest'))).value;for(const a of m.assets)assert.equal((await http(a.rightsURL)).status,200);const text=JSON.stringify(q)+JSON.stringify(m)+JSON.stringify(p);assert.ok(!text.includes('meridian-data://'));assert.ok(!text.includes('native-window.tif'));assert.ok(!text.includes('nrw-vegetation-full-features.json'));assert.ok(!text.includes('C:\\Users'));});
test('H22 consumer code isolation and native portrayal geometry/raster',async()=>{for(const file of ['view.mjs','http-consumer.mjs','session-consumer.mjs']){const code=readFileSync(resolve(import.meta.dirname,'../client',file),'utf8');assert.ok(!/from ["']\.\.|readFile|catalogue|generations\.mjs|openEvidence|derivations\.mjs/.test(code));}const m=(await http(route(g1,'manifest'))).value;assert.equal(m.layers.worldcover.grid.cells,185036);const n=await http(m.assets.find(a=>a.family==='nrw').url);assert.equal(n.value.features.length,193);assert.equal(n.value.features[0].properties.nativeSupport.crs,'EPSG:27700');assert.equal((await fetch(url+'/')).status,200);});
test('H23 corruption fails explicit before asset delivery without touching source',async()=>{const isolated=join(dir,'bad');cloneStore(isolated);const a=initial.value.serving.assets.find(a=>a.family==='worldcover');writeFileSync(join(isolated,'artifacts',a.id+'.png'),'safe corrupt fixture');assert.throws(()=>load(isolated),e=>e.code==='serving-integrity');});
test('H24 malformed/oversized/wrong-origin requests rejected',async()=>{assert.equal((await query(g1,{property:'nrw-native'})).status,400);const r=await fetch(url+route(g1,'query'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload:'x'.repeat(65537)})});assert.equal(r.status,400);const o=await fetch(url+'/pilot/v1/current',{headers:{Origin:'http://external.invalid'}});assert.equal(o.status,400);});
test('all310 source hashes unchanged; S1/S2/S3 state not rewritten',()=>{assert.deepEqual(verifyArtifacts(initial.value.catalogue,initial.locators,DATA),{artifacts:310,bytes:42473107});assert.equal(encode(load(store,{generation:g1}).value),encode(initial.value));assert.equal(load(store,{generation:g2}).value.understanding.stage,'common');});
test('rebuild serving artifacts/manifests deterministic excluding publication parent',async()=>{const built=await buildDelivery({store});assert.deepEqual(built.value.serving,initial.value.serving);assert.equal(built.value.capabilities.mixedFamilyUpdate,false);});

test('H24 real shared worker queue32 rejects overflow and same-evidence generations reuse initialization',async()=>{const session=new NativeSession();let x,y;try{x=await openEvidence({store,generation:g1,nativeSession:session});y=await openEvidence({store,generation:g2,nativeSession:session});assert.equal(x.metadata.families.nrw.featureCount,y.metadata.families.nrw.featureCount);const pending=Array.from({length:32},()=>session.call({operation:'query',point:summit,crs:'EPSG:27700'}));assert.throws(()=>session.call({operation:'query',point:summit,crs:'EPSG:27700'}),e=>e.code==='worker-unavailable');const answers=await Promise.all(pending);assert.ok(answers.every(a=>a.worldcover.code===30));}finally{x?.close();y?.close();session.close();}});
