// Assessment-only process instrumentation. No pilot/source files are changed.
import fs from 'node:fs';import {registerHooks,syncBuiltinESMExports} from 'node:module';import {createHash} from 'node:crypto';import {performance} from 'node:perf_hooks';import {fileURLToPath} from 'node:url';
const digest=b=>createHash('sha256').update(b).digest('hex');
export const plan=JSON.parse(fs.readFileSync(new URL('./plan.json',import.meta.url),'utf8'));
let active=null;const nativeParse=JSON.parse;
function call(name,fn,args){if(!active)return fn(...args);const a=active,start=performance.now(),frame={child:0};a.stack.push(frame);let value;try{return value=fn(...args);}finally{const ms=performance.now()-start;a.stack.pop();if(a.stack.length)a.stack.at(-1).child+=ms;const v=a.ops[name]??={calls:0,inclusiveMs:0,exclusiveMs:0,bytes:0};v.calls++;v.inclusiveMs+=ms;v.exclusiveMs+=ms-frame.child;if(name==='readFileSync' && value!==undefined){const bytes=typeof value==='string'?Buffer.byteLength(value):value.length;v.bytes+=bytes;const key=a.stack.some(x=>x.label==='verifyArtifacts'||x.label==='verifyDelivery'||x.label==='payloadSweep')?'payload':'metadata';a.reads[key]??={calls:0,bytes:0};a.reads[key].calls++;a.reads[key].bytes+=bytes;const path=String(args[0]).replaceAll('\\','/'),category=['membership','components','publications','generations','locators','artifacts'].find(k=>path.includes('/'+k+'/'))??key;a.files[category]??={calls:0,bytes:0};a.files[category].calls++;a.files[category].bytes+=bytes;}if(name==='sha'){const bytes=typeof args[0]==='string'?Buffer.byteLength(args[0]):args[0].length;v.bytes+=bytes;const k=typeof args[0]==='string'?'text':'buffer';a.hashes[k]??={calls:0,bytes:0};a.hashes[k].calls++;a.hashes[k].bytes+=bytes;}if(name==='parse')v.bytes+=Buffer.byteLength(String(args[0]));}}
function phase(name,fn,args){if(!active)return fn(...args);const a=active;return call(name,(...values)=>{a.stack.at(-1).label=name;return fn(...values);},args);}
const key=Symbol.for('atlas.integrity.cost');globalThis[key]={phase,call};
export function install(){for(const name of ['existsSync','realpathSync','statSync','readFileSync','writeFileSync','openSync','fsyncSync','renameSync']){const fn=fs[name];fs[name]=(...args)=>call(name,fn,args);}syncBuiltinESMExports();JSON.parse=(...args)=>call('parse',nativeParse,args);
 const targets={'pilots/atlas/tryfan/catalogue.mjs':['validateCatalogue','verifyArtifacts'],'pilots/atlas/tryfan/generations.mjs':['validateGeneration','canonicalGeneration','currentId','load','register','publish'],'pilots/atlas/tryfan/dependencies.mjs':['validateDependencies'],'pilots/atlas/tryfan/update-schema.mjs':['validateUpdate','validateTransition'],'pilots/atlas/tryfan/delivery-schema.mjs':['validateDelivery','verifyDelivery'],'scripts/atlas/component-membership/core.mjs':['membership','resolveGeneration','load','publish']};
 registerHooks({load(url,context,next){const v=next(url,context);if(!url.startsWith('file:'))return v;const file=fileURLToPath(url).replaceAll('\\','/');let rel=Object.keys(targets).find(p=>file.endsWith('/'+p));if(file.endsWith('/pilots/atlas/tryfan/identity.mjs'))rel='pilots/atlas/tryfan/identity.mjs';if(!rel)return v;let s=String(v.source);if(digest(Buffer.from(s))!==plan.authoritativeHashes[rel])throw Error('Instrumented authoritative source drift: '+rel);
 const names=targets[rel]??['sha','encode'];for(const n of names){if(rel.endsWith('/identity.mjs')){const token='export const '+n+' =';if(!s.includes(token))throw Error('Missing function '+n);s=s.replace(token,'const __cost_'+n+' =');}else{const token='export function '+n+'(';if(!s.includes(token))throw Error('Missing function '+n);s=s.replace(token,'function __cost_'+n+'(');}s+='\nexport const '+n+'=(...args)=>globalThis[Symbol.for("atlas.integrity.cost")].phase("'+n+'",__cost_'+n+',args);\n';}return {...v,source:s};}});
}
export function measure(fn){if(active)throw Error('Nested top-level sample');const start=performance.now(),a={ops:{},reads:{},files:{},hashes:{},stack:[]};active=a;try{const value=fn();return {value,milliseconds:performance.now()-start,ops:a.ops,reads:a.reads,files:a.files,hashes:a.hashes,RSS:process.memoryUsage().rss};}finally{active=null;}}
export function sweep(items,root,sha,safePath){return phase('payloadSweep',()=>{let bytes=0;for(const a of items){const p=safePath(root,a.path);if(!fs.statSync(p).isFile()||fs.statSync(p).size!==a.bytes)throw Error('payload-size');const b=fs.readFileSync(p);if(sha(b)!==a.sha256)throw Error('payload-integrity');bytes+=b.length;}return {artifacts:items.length,bytes};},[]);}
