"""Assessment regression: protects every pre-existing non-navigation tracked byte."""
from pathlib import Path
import json,hashlib,subprocess,sys,os,re
from urllib.parse import unquote
R=Path(__file__).resolve().parents[3];H=Path(__file__).parent;BASE='eb3459353b40a1305928a870645d5d5d3be3d114';OUT='docs/research/atlas-integrity-cost-validation.json'
sys.stdout.reconfigure(encoding='utf-8');sys.path.insert(0,str(R/'scripts/atlas/regional-pilot-plan'));import check_plan as P
NAV={'docs/architecture.md','docs/product-direction.md','docs/development-log.md','docs/research/atlas-research-map.md','docs/research/atlas-research-state.md'};LOG=Path('C:/Users/gbsam/Documents/Codex/atlas-integrity-cost-v1/regression');LOG.mkdir(parents=True,exist_ok=True)
checks=[];errors=[];commands=[]
def check(name,ok):
 checks.append(dict(check=name,passed=bool(ok)))
 if not ok:errors.append(name)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads((R/p).read_text(encoding='utf-8'))
def git(*args):return subprocess.check_output(['git',*args],cwd=R,text=True,encoding='utf-8')
tracked=git('ls-tree','-r','--name-only',BASE).splitlines();preserve=[p for p in tracked if p not in NAV];tree={l.split('\t')[1]:l.split()[2] for l in git('ls-tree','-r',BASE).splitlines()}
def intact():
 hs=subprocess.check_output(['git','hash-object','--stdin-paths'],cwd=R,input='\n'.join(preserve)+'\n',text=True).splitlines();return len(hs)==len(preserve) and all(h==tree[p] for p,h in zip(preserve,hs))
check('all original non-navigation files unchanged before validation',intact());old=git('show',BASE+':docs/research/atlas-research-state.md');check('all42 research statuses unchanged',len(P.admission.canonical_rows(old))==42 and P.admission.canonical_rows(old)==P.admission.canonical_rows((R/'docs/research/atlas-research-state.md').read_text(encoding='utf-8')))
protected=read('docs/atlas/information-display-plan.json')['productionHashes'];check('all113 protected production hashes',len(protected)==113 and all(sha(R/p)==h for p,h in protected.items()))
b=read('docs/research/atlas-integrity-cost-baseline.json');store=P.DATA/'experiments/atlas/tryfan-regional-pilot-v1';check('all17 accepted store hashes unchanged',len(b['acceptedStoreHashes'])==17 and all(sha(store/p)==h for p,h in b['acceptedStoreHashes'].items()));before=P.admission.assess()['sources'];check('retained1575 files',before['uniqueFiles']==1575)
plan=read('scripts/atlas/integrity-cost/plan.json');x=read('docs/research/atlas-integrity-cost-results.json');d=read('docs/research/atlas-integrity-cost-decisions.json');check('frozen plan before implementation',sha(H/'plan.json')=='48f3cc4b0c3ae8cf2da7d5494ef4352b5d1f045bbca165b820b6ea8c6baaafce'==x['planSha256']);check('all original validation guards unchanged',all(sha(R/p)==h for p,h in plan['authoritativeHashes'].items()));check('all timed code pinned',all(sha(H/p)==h for p,h in x['codeHashes'].items()));check('all raw measurements pinned',all(sha(Path(r['path']))==r['sha256'] for r in x['rawFiles']));check('isolated raw state',all(Path(r['path']).resolve().is_relative_to(Path(plan['stateRoot']).resolve()) for r in x['rawFiles']));check('14 cases five repeats both modes',len(x['node'])==14 and all(len(c['observations'][m]['samples'])==5 for c in x['node'] for m in ['plain','meter']));check('plain-meter scientific outcomes match',all([s['value'] for s in c['observations']['plain']['samples']]==[s['value'] for s in c['observations']['meter']['samples']] for c in x['node']));check('all sample and complete-sequence costs retained',all(s['milliseconds']>0 for c in x['node'] for m in ['plain','meter'] for s in c['observations'][m]['samples']));check('current integrity no receipt optimization',all(r['validation']['counter']['componentIntegrity']==192 and r['commit']['counter']['componentIntegrity']==192 for c in x['metadata']['meter']['rows'] if c['kind']=='sequence' for rep in c['repeats'] for r in rep['rows']));check('all14 failure controls preserve root',len(x['failures'])==9 and len(x['metadata']['plain']['failures'])==5 and all(f['rootPreserved'] for f in x['failures']+x['metadata']['plain']['failures']));check('abrupt exit at actual pre-switch boundary',next(f for f in x['failures'] if f['kind']=='pre-switch-interruption')['exit']==91);check('five independent fresh loads same identities',len(x['fresh'])==5 and all(f['sample']['value']==x['node'][3]['observations']['plain']['samples'][0]['value'] for f in x['fresh']));check('full provisional default and closed receipts',d['fullValidationDefault'] and d['receiptOptimisationClosed']);check('four conclusion classes',set(r['classification'] for r in d['records'])=={'DECIDE NOW','PROVISIONAL DIRECTION','DEFER PENDING EVIDENCE','REJECT'});check('unstarted exactly-one regional next task',d['nextTaskStatus']=='NOT BEGUN' and d['nextTask']=='Atlas retained regional expansion and source-accountability assessment');check('resolved judgement matches',x['decision']==d['decision']=='C - ASSESSMENT RESOLVED')
def run(name,args):
 q=subprocess.run(args,cwd=R,capture_output=True,text=True,encoding='utf-8',errors='replace',env={**os.environ,'PYTHONIOENCODING':'utf-8'});(LOG/(name+'.log')).write_text(q.stdout+q.stderr,encoding='utf-8',newline='\n');check(name,q.returncode==0);n=re.search(r'^(?:#|\u2139) tests (\d+)',q.stdout,re.M) or re.search(r'Ran (\d+) tests?',q.stderr);commands.append(dict(name=name,args=args,exitCode=q.returncode,tests=int(n[1]) if n else None));print(name,q.returncode,flush=True)
 if q.returncode:print((q.stdout+q.stderr)[-2200:],flush=True)
run('cost-reproduction',[sys.executable,str(H/'run.py'),'--check']);run('cost-measurement-tests',[sys.executable,str(H/'test_measurement.py')])
# Exact established checks from the last accepted proof; no old receipt is rewritten.
for c in read('docs/research/atlas-validation-packing-validation.json')['commands']:run(c['name'],c['args'])
changed=sorted(set(git('diff',BASE,'--name-only').splitlines()+git('ls-files','--others','--exclude-standard').splitlines()))
allowed={OUT,*['docs/research/atlas-integrity-cost'+s for s in ['.md','-baseline.json','-results.json','-decisions.json']]}|{'scripts/atlas/integrity-cost/'+p for p in ['plan.json','README.md','meter.mjs','worker.mjs','metadata.py','metadata-worker.py','failures.mjs','run.py','validate.py','test_measurement.py','report.py']}
check('assessment-only changed paths',all(p in allowed|NAV for p in changed));check('small reports no payloads committed',all((R/p).stat().st_size<(2000000 if p.endswith('-results.json') else 150000) and not p.endswith(('.png','.tif','.npz','.bin','.db','.pyc')) for p in changed if p not in NAV));text=(R/'docs/research/atlas-integrity-cost.md').read_text(encoding='utf-8');check('all33 required report sections',list(map(int,re.findall(r'^## (\d+)\.',text,re.M)))==list(range(1,34)));check('decision records referenced',all(r['id'] in text for r in d['records']));check('development log append-only',(R/'docs/development-log.md').read_text(encoding='utf-8').startswith(git('show',BASE+':docs/development-log.md')+'\n'))
for p in NAV:check('result and next in '+p,d['nextTask'] in (R/p).read_text(encoding='utf-8') and d['decision'] in (R/p).read_text(encoding='utf-8'))
missing=[]
for p in changed:
 if not p.endswith('.md'):continue
 text=(R/p).read_text(encoding='utf-8')
 if p=='docs/development-log.md':text=text[len(git('show',BASE+':docs/development-log.md')):]
 for link in re.findall(r'\]\(([^)]+)\)',text):
  if link.startswith(('http:','https:','mailto:')):continue
  target=unquote(link.strip('<>')).split('#')[0];f=(R/p).parent/target if target else R/p
  if not f.exists() and f.resolve()!=(R/OUT).resolve():missing.append([p,link])
check('local report references resolve',not missing);check('all original non-navigation files unchanged after regression',intact());check('sources unchanged after regression',P.admission.assess()['sources']==before);check('accepted store unchanged after regression',all(sha(store/p)==h for p,h in b['acceptedStoreHashes'].items()));check('all protected production after regression',all(sha(R/p)==h for p,h in protected.items()));state=json.loads(subprocess.check_output(['node','pilots/atlas/tryfan/cli.mjs','inspect'],cwd=R,text=True,encoding='utf-8'));check('published generation and310 hashes unchanged',state['generation']==b['current'] and state['verification']==b['sources'])
receipt=dict(schema='atlas-integrity-cost-validation/v1',startingCheckpoint=BASE,checks=checks,errors=errors,commands=commands,testCount=sum(c['tests'] or 0 for c in commands),preservedTrackedFiles=len(preserve),changedPaths=changed,canonicalThreads=42,protectedHashes=113,acceptedPilotUnchanged=not errors,sourceAdmission=before,retainedVerification=state['verification'],publishedGeneration=state['generation'],missingReferences=missing,decision=d['decision'],nextTask=d['nextTask'],experimentHashes={p:sha(R/p) for p in changed if p not in NAV and p!=OUT});(R/OUT).write_text(json.dumps(receipt,ensure_ascii=False,sort_keys=True,indent=2)+'\n',encoding='utf-8',newline='\n');print(json.dumps(dict(checks=len(checks),tests=receipt['testCount'],errors=errors)),flush=True)
if errors:raise SystemExit(1)
