/** Bounded workload measurement through public runtime interfaces; payloads external. */
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {openAtlas,createWorld,inspectEvidence,registerEvidence,planEvidenceUpdate,stageEvidenceUpdate,validateStage,publishStage} from './index.ts';
import {resolveAuthoritative} from './authority.ts';import {digest} from './lifecycle-model.ts';import {queries,semantic} from './exe-cases.mjs';
const R=fileURLToPath(new URL('../../',import.meta.url)),base=JSON.parse(fs.readFileSync(path.join(R,'docs/research/atlas-local-exe-baseline.json'))),data=path.resolve(R,'../meridian-data');
const timed=async fn=>{const start=performance.now(),result=await fn();return {milliseconds:performance.now()-start,result}};
const stat=values=>({median:[...values].sort((a,b)=>a-b)[Math.floor(values.length/2)],min:Math.min(...values),max:Math.max(...values)});
if(process.argv[2]==='--replay'){
 const cfg=JSON.parse(fs.readFileSync(process.argv[3])),samples=[],start=performance.now();
 for(const generation of cfg.history){const c={...cfg,generation,catalogueRoot:cfg.catalogueRoot+generation},opened=await timed(()=>openAtlas(c)),x=opened.result;try{
  const built=await timed(()=>x.buildCatalogue({qualified:true})),all=await x.retrieve({}),exe=all.results.filter(r=>r.region==='exe'),ks=exe[0]?.knowledgeRef?all.documents[exe[0].knowledgeRef].identity:null;
  const matrix=queries.filter(q=>!q.relatedTo||exe.length).concat(ks?[{region:'exe',knowledge:{revision:ks}},{region:'exe',waterTime:{role:'observation',unknown:true},knowledge:{revision:'0'.repeat(64)}},{region:'exe',waterTime:{role:'observation',unknown:true},knowledge:{revision:ks}}]:[]),rows=[];
  // Prior generation has no admitted water families; do not fabricate them.
  for(const q of matrix.filter(q=>exe.length||(!q.families?.some(f=>f.startsWith('water-'))&&!q.relatedTo))){const a=await timed(()=>x.retrieve(q)),b=await timed(()=>x.scanEvidence(q));if(digest(semantic(a.result))!==digest(semantic(b.result)))throw Error('Indexed/full mismatch');rows.push({queryIndex:rows.length,hash:digest(semantic(a.result)),indexedMs:a.milliseconds,scanMs:b.milliseconds,results:a.result.results.length,metrics:Object.fromEntries(['candidates','recordsConsidered','exactSpatialChecks','payloadReadCalls','decodedPayloadBytes','nativeSelectorPredicates','derivedCandidates','relationshipResults','canonicalMetadataReads','canonicalMetadataBytes','artifactMetadataReads','artifactMetadataBytes'].map(k=>[k,a.result.metrics[k]??0]))})}
  fs.unlinkSync(path.join(c.catalogueRoot,'current.json'));const rebuild=await timed(()=>x.buildCatalogue({qualified:true}));if(digest(semantic(all))!==digest(semantic(await x.retrieve({}))))throw Error('Rebuild changed evidence');
  samples.push({generation,openMs:opened.milliseconds,buildMs:built.milliseconds,built:built.result,rebuildMs:rebuild.milliseconds,validation:x.validation,exeSetup:x.nativeSetup.exe??null,counts:{source:all.results.filter(r=>r.evidenceClass==='source').length,derived:all.results.filter(r=>r.evidenceClass==='derived').length,exe:exe.length},relationships:all.relationships.length,answerBytes:Buffer.byteLength(JSON.stringify(all)),answerHash:digest(semantic(all)),queries:matrix.filter(q=>exe.length||(!q.families?.some(f=>f.startsWith('water-'))&&!q.relatedTo)),parentRss:process.memoryUsage().rss,rows});
 }finally{await x.close()}}
 console.log(JSON.stringify({pid:process.pid,samples,milliseconds:performance.now()-start}));
}else{
 const out=fs.mkdtempSync(path.resolve(R,'../../Codex/atlas-exe-measured-')),phases=[],allStart=performance.now();
 for(let repeat=0;repeat<3;repeat++){
  const c={dataRoot:data,publicationRoot:path.join(out,'world-'+repeat),catalogueRoot:path.join(out,'phase-cache-'+repeat),python:path.join(data,'earth-lab/.venv/Scripts/python.exe')};
  const initial=await timed(()=>createWorld(c,base.selectedWorld)),g0=initial.result.generation,old=resolveAuthoritative(c),inspection=await timed(()=>inspectEvidence(c,{family:'exe-water'})),request=inspection.result.templates.exe;
  const plan=await timed(()=>planEvidenceUpdate(c,request)),stage=await timed(()=>registerEvidence(c,{family:'exe-water'},request)),validation=await timed(()=>validateStage(c,stage.result.generation)),published=await timed(()=>publishStage(c,stage.result.generation));
  const next=resolveAuthoritative(c);for(const[k,v]of Object.entries(old.members))if(k!=='registrationLedger'&&next.members[k]!==v)throw Error('Unrelated region changed');
  const i=await inspectEvidence(c,{family:'exe-water'}),noop=await timed(()=>registerEvidence(c,{family:'exe-water'},i.templates.exe)),revision={...i.templates.exe,operation:'knowledge',explanation:'Controlled administrative accountability revision; no source/native or physical change.'};
  const revisionPlan=await timed(()=>planEvidenceUpdate(c,revision)),revised=await timed(()=>stageEvidenceUpdate(c,revision)),revisionPublished=await timed(()=>publishStage(c,revised.result.generation));
  const files=fs.readdirSync(c.publicationRoot,{recursive:true}).filter(p=>fs.statSync(path.join(c.publicationRoot,p)).isFile()),worldBytes=files.reduce((n,p)=>n+fs.statSync(path.join(c.publicationRoot,p)).size,0);
  phases.push({config:c,history:[g0,stage.result.generation,revised.result.generation],initialMs:initial.milliseconds,inspectionMs:inspection.milliseconds,inspection:inspection.result.metrics,nativeBytes:Buffer.byteLength(JSON.stringify(request.native)),nativeIdentity:digest(request.native),planningMs:plan.milliseconds,registrationMs:stage.milliseconds,stage:stage.result,validationMs:validation.milliseconds,validation:validation.result,publicationMs:published.milliseconds,published:published.result,noOpMs:noop.milliseconds,noop:{...noop.result,registration:{identity:noop.result.registration.identity,nativeIdentity:noop.result.registration.revision.nativeIdentity,sequence:noop.result.registration.revision.sequence}},revisionPlanMs:revisionPlan.milliseconds,revisionStageMs:revised.milliseconds,revisionPublishedMs:revisionPublished.milliseconds,revision:revised.result,unchangedComponents:Object.keys(old.members).length-1,worldFiles:files.length,worldBytes});
 }
 const runs=[];for(let repeat=0;repeat<3;repeat++){const cfg={...phases[0].config,history:phases[0].history,catalogueRoot:path.join(out,'replay-cache-'+repeat)},f=path.join(out,'replay-'+repeat+'.json');fs.writeFileSync(f,JSON.stringify(cfg));const p=spawnSync(process.execPath,[fileURLToPath(import.meta.url),'--replay',f],{cwd:R,encoding:'utf8',maxBuffer:32*1024*1024});if(p.status!==0)throw Error(p.stderr);runs.push(JSON.parse(p.stdout));}
 const expected=runs[0].samples.map(s=>[s.answerHash,s.rows.map(r=>r.hash)]);if(runs.some(r=>digest(r.samples.map(s=>[s.answerHash,s.rows.map(v=>v.hash)]))!==digest(expected)))throw Error('Fresh replay disagrees');
 const current=runs.map(r=>r.samples.at(-1)),summary={};for(const k of ['inspectionMs','planningMs','registrationMs','validationMs','publicationMs','noOpMs','revisionPlanMs','revisionStageMs','revisionPublishedMs'])summary[k]=stat(phases.map(p=>p[k]));for(const k of ['openMs','buildMs','rebuildMs'])summary[k]=stat(current.map(s=>s[k]));
 const results={checkpoint:base.checkpoint,planSha256:base.planSha256,agreement:true,comparisons:runs.reduce((n,r)=>n+r.samples.reduce((m,s)=>m+s.rows.length,0),0),freshProcesses:3,phases,runs,summary,elapsedMs:performance.now()-allStart,environment:{node:process.version,platform:process.platform,cpu:os.cpus()[0].model,logicalProcessors:os.cpus().length,totalMemoryBytes:os.totalmem(),outputRoot:out}};
 fs.writeFileSync(path.join(R,'docs/research/atlas-local-exe-results.json'),JSON.stringify(results)+'\n');console.log(JSON.stringify({outputRoot:out,comparisons:results.comparisons,summary}));
}
