import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {openAtlas,inspectEvidence,registerEvidence,stageEvidenceUpdate,planEvidenceUpdate,publishStage,validateStage,recoverWorld} from './index.ts';
import {describeExe} from './exe-model.ts';import {resolveAuthoritative} from './authority.ts';import {stageObject} from './publication.ts';
import {queries,semantic,ids,literal,point,area} from './exe-cases.mjs';
const R=path.resolve(import.meta.dirname,'../..'),data=path.resolve(R,'../meridian-data'),out=fs.mkdtempSync(path.resolve(R,'../../Codex/atlas-exe-tests-'));
const baseline=JSON.parse(fs.readFileSync(path.join(R,'docs/research/atlas-local-exe-baseline.json'))),c={dataRoot:data,publicationRoot:path.join(out,'world'),catalogueRoot:path.join(out,'cache'),python:path.join(data,'earth-lab/.venv/Scripts/python.exe')};fs.cpSync(baseline.selectedWorld,c.publicationRoot,{recursive:true});
let childId=0;function child(code){const f=path.join(out,'child-'+childId+++'.mjs');fs.writeFileSync(f,code.replaceAll('./runtime/atlas/','file:///'+R.replaceAll('\\','/')+'/runtime/atlas/'));return spawnSync(process.execPath,[f],{cwd:R,encoding:'utf8',maxBuffer:32*1024*1024})}
const current=()=>JSON.parse(fs.readFileSync(path.join(c.publicationRoot,'current.json'))).generation;
test('retained Exe water evidence through the shared runtime',async t=>{
 const before=resolveAuthoritative(c),g0=before.generation,inspected=await inspectEvidence(c,{family:'exe-water'}),request=inspected.templates.exe;
 await t.test('31 pinned receipts and66 retained files; eight accountable selectors',()=>{assert.equal(inspected.metrics.sourceHashOperations,31);assert.equal(inspected.metrics.sourceBytesHashed,9892590);assert.equal(inspected.metrics.directoryHashOperations,66);assert.equal(request.native.records.length,8);assert.equal(request.native.records.filter(r=>r.evidenceClass==='derived').length,2)});
 for(const [name,mutate] of [
 ['source',r=>{delete r.native.sources}],['rights',r=>{r.native.records[0].rights.attribution=[]}],['fingerprint',r=>{r.native.sources['wfd.geojson'].sha256='0'.repeat(64)}],['classification',r=>{r.native.records[0].evidence.claim.result={kind:'assertion',value:{kind:'detection',outcome:'absent'}}}],['time',r=>{r.native.records[0].waterTime[0].extent.start='2024-03-02'}],['CRS',r=>{r.native.records[0].support.crs='EPSG:2056'}],['support',r=>{r.native.records[0].support.geometry={type:'Point',coordinates:[0,0]}}],['lineage',r=>{r.native.records[0].provenance={}}],['stale generation',r=>{r.expectedGeneration='0'.repeat(64)}],['duplicate',r=>{r.native.records.push(r.native.records[0])}],['operation',r=>{r.operation='physical-change'}]
 ])await t.test('reject invalid '+name+' registration without root advancement',async()=>{const r=structuredClone(request);mutate(r);await assert.rejects(stageEvidenceUpdate(c,r));assert.equal(current(),g0)});
 const plan=await planEvidenceUpdate(c,request),stage=await registerEvidence(c,{family:'exe-water'},request);
 await t.test('dry plan and staging reuse all32 terrain outputs; unpublished pin rejected',async()=>{assert.equal(plan.reused,32);assert.deepEqual(stage.affected,[]);assert.equal(current(),g0);await assert.rejects(openAtlas({...c,generation:stage.generation}));assert.equal((await validateStage(c,stage.generation)).status,'fully-validated-unpublished')});
 await t.test('interruption before root leaves Exe invisible',async()=>{await assert.rejects(publishStage(c,stage.generation,{failAt:'beforeRoot'}));assert.equal(current(),g0)});
 await publishStage(c,stage.generation);const g1=current(),after=resolveAuthoritative(c);
 await t.test('only Exe component and ledger change; terrain/artifact identities reused',()=>{for(const[k,v]of Object.entries(before.members))if(k!=='registrationLedger')assert.equal(after.members[k],v);assert.deepEqual(after.values.terrainDerived,before.values.terrainDerived);assert.equal(Object.keys(after.members).length,Object.keys(before.members).length+1)});
 const x=await openAtlas(c);let expected;
 try{
 await t.test('disposable catalogue holds89 selectors/34 edges without payload copying',async()=>{const b=await x.buildCatalogue({qualified:true});assert.equal(b.records,89);assert.equal(b.relationships,34);assert.equal((await x.verifyCatalogue({qualified:true})).records,89)});
 expected=semantic(await x.retrieve({}));
 for(const[i,q]of queries.entries())await t.test('indexed/full exact qualified query '+i,async()=>{assert.deepEqual(semantic(await x.retrieve(q)),semantic(await x.scanEvidence(q)));if((!q.region||q.region==='exe')&&!q.point&&!q.area&&!q.time&&!q.relatedTo)assert.deepEqual(ids(await x.retrieve({...q,region:q.region??'exe'})),literal({...q,region:q.region??'exe'},request.native.records))});
 await t.test('independent accepted counts, codes and reference/event qualifiers',async()=>{const a=await x.retrieve({region:'exe'});assert.equal(a.results.length,8);assert.equal(a.results.filter(r=>r.evidenceClass==='source').length,6);for(const month of ['2024-03','2024-09']){const r=a.results.find(r=>r.identity==='exe:'+month+':support'),b=a.documents[r.evidenceRef];assert.deepEqual(b.counts,month==='2024-03'?{'0':0,'1':0,'2':77}:{'0':76,'1':1,'2':0});assert.equal(b.selectedCellCentres,77);assert(a.documents[r.provenanceRef].method.revision);assert.equal(r.relationshipRefs.length,1)}const march=a.results.find(r=>r.identity==='exe:2024-03:point'),sept=a.results.find(r=>r.identity==='exe:2024-09:point');assert.equal(a.documents[march.evidenceRef].cell.code,2);assert.equal(a.documents[sept.evidenceRef].cell.code,0);assert.equal(a.documents[sept.evidenceRef].result.reason,'no-observation');assert.equal((await x.retrieve({region:'exe',waterTime:{role:'observation',unknown:true}})).results.length,2);assert.equal((await x.retrieve({region:'exe',waterTime:{role:'reference',start:'2019',end:'2019'}})).results[0].identity,'exe:wfd')});
 await t.test('unknown observation predicate must still apply knowledge filtering',async()=>{assert.equal((await x.retrieve({region:'exe',waterTime:{role:'observation',unknown:true},knowledge:{revision:'0'.repeat(64)}})).results.length,0)});
 await t.test('independent native geometry oracle: P1 matches WFD and containing cells, not distant RFO or centre-summary points',async()=>{assert.deepEqual(ids(await x.retrieve({region:'exe',point,crs:'EPSG:27700'})),['exe:2024-03:point','exe:2024-03:product','exe:2024-09:point','exe:2024-09:product','exe:wfd']);assert.deepEqual(ids(await x.retrieve({region:'exe',area,crs:'EPSG:27700'})),request.native.records.map(r=>r.identity).filter(id=>id!=='exe:rfo').sort());const p=spawnSync(c.python,[path.join(R,'runtime/atlas/exe-oracle.py'),data],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);const oracle=JSON.parse(p.stdout);assert.equal(oracle.polygons.wfd.pointP1,true);assert.equal(oracle.polygons.rfo.areaP1,0);const centre=oracle.monthly['2024-03'].centres[0];assert.equal((await x.retrieve({region:'exe',evidenceClass:'derived',point:centre,crs:'EPSG:27700'})).results.length,2)});
 await t.test('published RFO event interval is day-qualified, not local inundation seconds',async()=>{assert.deepEqual(ids(await x.retrieve({region:'exe',waterTime:{role:'event',start:'2014-02-04',end:'2014-02-05'}})),['exe:rfo']);assert.deepEqual(ids(await x.retrieve({region:'exe',waterTime:{role:'event',start:'2014-02-06',end:'2014-02-07'}})),[])});
 await t.test('all result documents preserve source/prepared/rights/native geometry/time',async()=>{const a=await x.retrieve({region:'exe'});for(const r of a.results){assert.equal(r.componentIdentity,a.members.exeRegistration);for(const ref of [r.evidenceRef,r.provenanceRef,r.qualificationRef,r.rightsRef,r.knowledgeRef])assert(a.documents[ref]);assert(r.support.crs);const p=a.documents[r.provenanceRef];assert(p.source.sha256);assert(p.source.path.startsWith('meridian-data/'));assert(p.method.revision);assert.equal(p.physicalChangeInferred,false);assert(a.documents[r.rightsRef].attribution.length)}});
 const unsupported=[{currentWater:true},{physicalAbsence:true},{families:['streamflow']},{representation:'ground-truth'},{region:'exe',point,crs:'EPSG:2056'},{region:'exe',area:[2,3,1,4],crs:'EPSG:27700'},{waterTime:{role:'observation',start:'2024',end:'2024'}},{waterTime:{role:'event',start:'2024-01-01T00:00:00Z',end:'2024-01-02T00:00:00Z'}},{waterTime:{role:'event',start:'2024-02-02',end:'2024-02-01'}},{waterTime:{role:'observation',absent:true}},{waterTime:{role:'event',unknown:false}},{knowledge:{unknown:false}},{relatedTo:{identity:'absent',direction:'inputs',depth:'direct'}}];
 for(const[i,q]of unsupported.entries())await t.test('unsupported scientific or malformed predicate '+i,async()=>{await assert.rejects(x.retrieve(q))});
 for(const failAt of ['beforeInstall','beforePointer'])await t.test('interrupted catalogue '+failAt+' preserves prior answers',async()=>{const pointer=fs.readFileSync(path.join(c.catalogueRoot,'current.json'),'utf8');await assert.rejects(x.buildCatalogue({qualified:true,failAt}));assert.equal(fs.readFileSync(path.join(c.catalogueRoot,'current.json'),'utf8'),pointer);assert.deepEqual(semantic(await x.retrieve({})),expected)});
 await t.test('corrupt catalogue rejected and explicitly rebuildable',async()=>{const epoch=JSON.parse(fs.readFileSync(path.join(c.catalogueRoot,'current.json'))).epoch;fs.appendFileSync(path.join(c.catalogueRoot,'epochs',epoch,'index.sqlite'),'bad');await assert.rejects(x.retrieve({}));await x.buildCatalogue({qualified:true});assert.deepEqual(semantic(await x.retrieve({})),expected)});
 await t.test('no match is an honest gap, not dry/absent water',async()=>{const a=await x.retrieve({region:'exe',identity:'absent'});assert.equal(a.gap.physicalAbsenceInferred,false);assert.equal(a.results.length,0)});
 }finally{await x.close()}
 await t.test('repeat exact registration is no-op',async()=>{const i=await inspectEvidence(c,{family:'exe-water'}),r=await registerEvidence(c,{family:'exe-water'},i.templates.exe);assert.equal(r.status,'no-op');assert.equal(current(),g1)});
 const info=await inspectEvidence(c),revision={...request,operation:'knowledge',expectedGeneration:g1,expectedRevision:info.registrations.exe.identity,explanation:'Administrative local accountability clarification only; no new observation, code, support or physical change.'},s2=await stageEvidenceUpdate(c,revision);
 await t.test('administrative Exe knowledge supersession reuses all32 numerical derivations',()=>{assert.equal(s2.reused,32);assert.deepEqual(s2.affected,[]);assert.deepEqual(s2.requalified,[])});
 await publishStage(c,s2.generation);const g2=current();
 await t.test('knowledge revision distinct from unchanged source/physical time; old pin remains exact',async()=>{const y=await openAtlas(c);try{await assert.rejects(y.retrieve({}),/another generation/);await y.buildCatalogue({qualified:true});const newAnswer=await y.retrieve({});for(const old of expected.results){const now=newAnswer.results.find(r=>r.key===old.key);for(const k of ['evidenceRef','support','temporal','provenanceRef','rightsRef','revision'])assert.deepEqual(now[k],old[k]);if(old.region==='exe')assert.notEqual(now.knowledgeRef,old.knowledgeRef);else assert.equal(now.knowledgeRef,old.knowledgeRef)}fs.unlinkSync(path.join(c.catalogueRoot,'current.json'));await y.buildCatalogue({qualified:true});assert.deepEqual(semantic(await y.retrieve({})),semantic(newAnswer))}finally{await y.close()}const old=await openAtlas({...c,generation:g1,catalogueRoot:path.join(out,'old')});try{await old.buildCatalogue({qualified:true});assert.deepEqual(semantic(await old.retrieve({})),expected)}finally{await old.close()}});
 await t.test('three fresh processes reproduce pre/post/revised publication histories',()=>{let previous;for(let i=0;i<3;i++){const p=child(`import{openAtlas}from'./runtime/atlas/index.ts';import{digest}from'./runtime/atlas/lifecycle-model.ts';import{semantic}from'./runtime/atlas/exe-cases.mjs';const rows=[];for(const generation of ${JSON.stringify([g0,g1,g2])}){const x=await openAtlas({...${JSON.stringify(c)},generation,catalogueRoot:${JSON.stringify(path.join(out,'fresh'))}+generation});try{await x.buildCatalogue({qualified:true});const a=await x.retrieve({});rows.push([generation,digest(semantic(a)),a.results.filter(r=>r.region==='exe').length]);}finally{await x.close()}}console.log(JSON.stringify(rows));`);assert.equal(p.status,0,p.stderr);if(previous)assert.equal(p.stdout,previous);previous=p.stdout;assert.deepEqual(JSON.parse(p.stdout).map(r=>r[2]),[0,8,8])}});
 await t.test('abrupt publication restart retains root and validates recovery',async()=>{const i=await inspectEvidence(c),s=await stageEvidenceUpdate(c,{...revision,expectedGeneration:g2,expectedRevision:i.registrations.exe.identity});const p=child(`import{publishStage}from'./runtime/atlas/index.ts';await publishStage(${JSON.stringify(c)},'${s.generation}',{failAt:'crashBeforeRoot'});`);assert.equal(p.status,91,p.stderr);assert.equal(current(),g2);recoverWorld(c);await assert.rejects(openAtlas({...c,generation:s.generation}));});
 for(const kind of ['missing','tamper','closure','cycle'])await t.test('canonical '+kind+' update remains unpublished',async()=>{const s=resolveAuthoritative(c),values=structuredClone(s.values);if(kind==='closure')delete values.exeRegistration;else if(kind==='cycle')values.registrationLedger.active.exe=values.registrationLedger.active.tryfan;else values.exeRegistration.records[0].provenance.source={sha256:'0'.repeat(64)};const staged=stageObject(c.publicationRoot,s,values);await assert.rejects(publishStage(c,staged));assert.equal(current(),g2)});
 await t.test('isolated retained source missing/tampered fails; no accepted source touched',async()=>{const temp=path.join(out,'isolated-data'),src=path.join(data,'derived/atlas/water-check-v1'),dest=path.join(temp,'derived/atlas/water-check-v1');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.cpSync(src,dest,{recursive:true});const file=path.join(dest,'monthly-2024-03.tif'),bytes=fs.readFileSync(file);fs.unlinkSync(file);await assert.rejects(describeExe({...c,dataRoot:temp}));fs.writeFileSync(file,bytes);fs.appendFileSync(file,'bad');await assert.rejects(describeExe({...c,dataRoot:temp}));});
});
