// Frozen real-population full/scoped comparison and retained publication sequence.
import fs from 'node:fs';import {join} from 'node:path';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
import * as D from './integration.mjs';import {encode,sha} from '../../../pilots/atlas/tryfan/identity.mjs';
const M=D.M,matrix=JSON.parse(fs.readFileSync(join(M.H,'matrix.json'),'utf8')),store=join(M.plan.stateRoot,'measured-'+Date.now());
const initial=performance.now(),seed=await D.seed(store),seedMilliseconds=performance.now()-initial,baseContexts=D.contexts(seed.value),baseStates=D.states(seed.value),density=M.density(baseContexts,baseStates),observations=[];
for(const c of matrix.cases)for(let repeat=0;repeat<matrix.repetitions;repeat++){
 const region=c.region??'riffelhorn',before=baseContexts[region],ctx=M.change(before,c),old=baseStates[region];
 const t=performance.now(),statuses=M.assess(ctx,old),assessMilliseconds=performance.now()-t,expected=M.expectedAffected(before,ctx,old),actual=Object.values(statuses).filter(a=>a.status==='stale').map(a=>a.id).sort();assert.deepEqual(actual,expected,c.id);
 const full=await M.recompute(ctx,M.empty(region),{full:true}),selective=await M.recompute(ctx,old);assert.deepEqual(M.currentContent(selective.state),M.currentContent(full.state));
 const changed=Object.keys(old.active).filter(id=>old.active[id]!==selective.state.active[id]).sort();assert.deepEqual(changed,expected,c.id);const other=region==='tryfan'?'riffelhorn':'tryfan', assembled={...baseStates,[region]:selective.state};assert.deepEqual(assembled[other],baseStates[other]);assert.equal(Object.keys(assembled[other].active).length,other==='tryfan'?4:180);
 observations.push({case:c.id,region,repeat,agreement:true,expectedAffected:expected,changed:changed.length,reused:Object.keys(old.active).length-changed.length,assessMilliseconds,full:full.measurement,scoped:selective.measurement});console.log(c.id,repeat,'affected',changed.length);
}
let value=structuredClone(seed.value),history=[],publications=[],members=[],pinHashes={};
for(let n=0;n<matrix.publishedSequence.length;n++){
 const id=matrix.publishedSequence[n];if(n){const c=matrix.cases.find(c=>c.id===id),region=c.region??'riffelhorn';value[region+'DependencyState']=M.change(value[region+'DependencyState'],c);value[region+'Derived']=(await M.recompute(value[region+'DependencyState'],value[region+'Derived'])).state;}
 const staged=D.prepare(store,value,seed.locators,{ordinal:n+1,predecessor:history.at(-1)??null});
 if(n){assert.throws(()=>D.resolveGeneration(store,staged));for(const old of history){const p=await D.pin(store,old);assert.equal(M.digest(p.snapshot.value),pinHashes[old]);}}
 const t=performance.now(),p=await D.publish(store,staged);publications.push({...p,totalMilliseconds:performance.now()-t});history.push(staged);const pin=await D.pin(store,staged);pinHashes[staged]=M.digest(pin.snapshot.value);members.push(pin.snapshot.publication.members);
 for(const old of history){const q=await D.pin(store,old);assert.equal(M.digest(q.snapshot.value),pinHashes[old]);}
}
const fixture={store,history,pinHashes};fs.writeFileSync(join(store,'fixture.json'),encode(fixture));
const fresh=[];for(let n=0;n<3;n++){const began=performance.now(),p=spawnSync(process.execPath,[join(M.H,'worker.mjs'),'replay',store,join(store,'fixture.json')],{cwd:process.cwd(),encoding:'utf8',maxBuffer:4*1024*1024});assert.equal(p.status,0,p.stderr);const r=JSON.parse(p.stdout);assert.equal(r.current,history.at(-1));fresh.push({...r,processMilliseconds:performance.now()-began});}
const query=[];for(const g of [history[0],history[1],history.at(-1)]){const p=await D.pin(store,g);for(const [region,question]of [['tryfan','tryfan-summit|slope'],['riffelhorn','dtm-cluster-0-0|area-ratio'],['riffelhorn','dtm-seam-x-0|slope'],['riffelhorn','cover-0-0|counts']])for(let repeat=0;repeat<3;repeat++){const r=await D.measured(()=>p.result(region,question));assert.equal(r.value.generation,g);assert.equal(r.value.status,'fresh');query.push({generation:g,region,question,repeat,resultIdentity:r.value.result.revision,measurement:r.measurement});}}
const summary={schema:'atlas-regional-dependency-results/v1',startingCheckpoint:M.plan.startingCheckpoint,planSha256:sha(fs.readFileSync(join(M.H,'plan.json'))),matrixSha256:sha(fs.readFileSync(join(M.H,'matrix.json'))),implementationHashes:Object.fromEntries(['model.mjs','integration.mjs','sample.py','tryfan-worker.mjs','worker.mjs','prove.mjs'].map(f=>[f,sha(fs.readFileSync(join(M.H,f)))])),store,seedMilliseconds,density:{...density,edgeList:undefined},realSourceEvidence:{registeredTryfanArtifacts:310,registeredSwissInputs:12,preparedSwissArtifacts:6,consumedSwissFiles:5,acceptedTryfanInputRoots:2,activeDerived:184,SwissTerrainProbes:88,SwissCategoricalSupports:4,TryfanProbes:2},observations,publications,history,members,fresh,query,pinHashes,footprint:Object.fromEntries(['components','publications','membership','artifacts'].map(folder=>{const files=fs.readdirSync(join(store,folder));return [folder,{files:files.length,bytes:files.reduce((n,f)=>n+fs.statSync(join(store,folder,f)).size,0)}];})),agreement:true,decision:'C - PROOF SUCCESS',limits:'Real sparse probes, not exhaustive region/global scale. Knowledge notes are controlled administrative changes, not acquired source revisions. Full publication replay is proof-only oracle work and is included in total; current source checks remain population-wide. Node/Python sampled RSS, not aggregate peaks; logical decoded bytes exclude compressed GDAL blocks; independent count oracle extra reads recorded; OS cache uncontrolled.'};
fs.writeFileSync(join(M.H,'../../../docs/research/atlas-regional-dependencies-graph.json'),JSON.stringify({schema:'atlas-regional-dependency-graph/v1',...density})+'\n');fs.writeFileSync(join(M.H,'../../../docs/research/atlas-regional-dependencies-results.json'),JSON.stringify(summary)+'\n');console.log(JSON.stringify({store,decision:summary.decision,pairedRuns:observations.length,density:summary.density,history}));
