import test,{before} from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import {join} from 'node:path';import {spawn,spawnSync} from 'node:child_process';import {createInterface} from 'node:readline';
import * as D from './integration.mjs';import {encode} from '../../../pilots/atlas/tryfan/identity.mjs';
const M=D.M;let seed,value,store,g1,g2,g3;
const local={id:'riff-local',kind:'note',region:'riffelhorn',family:'dtm',bounds:[2624350,1091350,2624350.5,1091350.5]},tryfan={id:'tryfan-local',kind:'note',region:'tryfan',family:'terrain',probe:'summit'};
function copied(label){const path=join(M.plan.stateRoot,'negative-'+label+'-'+Date.now());fs.cpSync(store,path,{recursive:true});D.owned(path);return path;}
function proposal(path,fn){const p=structuredClone(D.resolveGeneration(path,g3).publication);p.ordinal=4;p.predecessor=g3;fn(p);const body=encode(p),id=M.digest(p),f=join(path,'publications',id+'.json');if(fs.existsSync(f))assert.equal(fs.readFileSync(f,'utf8'),body);else fs.writeFileSync(f,body,{flag:'wx'});return id;}
before(async()=>{store=join(M.plan.stateRoot,'tests-'+Date.now());seed=await D.seed(store);value=structuredClone(seed.value);g1=D.prepare(store,value,seed.locators,{ordinal:1});await D.publish(store,g1);value.riffelhornDependencyState=M.change(value.riffelhornDependencyState,local);value.riffelhornDerived=(await M.recompute(value.riffelhornDependencyState,value.riffelhornDerived)).state;g2=D.prepare(store,value,seed.locators,{ordinal:2,predecessor:g1});await D.publish(store,g2);value.tryfanDependencyState=M.change(value.tryfanDependencyState,tryfan);value.tryfanDerived=(await M.recompute(value.tryfanDependencyState,value.tryfanDerived)).state;g3=D.prepare(store,value,seed.locators,{ordinal:3,predecessor:g2});await D.publish(store,g3);});
test('real current population and source distinctions',()=>{const d=M.density(D.contexts(seed.value),D.states(seed.value));assert.equal(d.nodes,293);assert.equal(d.edges,294);assert.equal(d.byType['derived-slope'],90);assert.equal(d.byType['derived-counts'],4);assert.equal(d.crossRegionEdges,0);assert.equal(seed.value.catalogue.artifacts.length,310);});
test('real seam fan-in and shared artifact fan-out',()=>{const d=M.density(D.contexts(seed.value),D.states(seed.value));assert.equal(d.fanIn[2],8);assert.equal(d.maximumSourceFanOut,36);assert.equal(d.maximumDepth,3);});
test('source height units are independently explicit without changing old fixture',()=>{for(const s of Object.values(value.riffelhornDependencyState.sources).filter(s=>s.family==='dtm')){assert.equal(s.unitEvidence.bandUnit,'metre');assert.match(s.unitEvidence.vertical,/LN02/);}assert.equal(value.riffelhornRegistration.preparationRevision,D.I.plan.regions.riffelhorn.preparedRevision);});
test('scoped and independently brute-expanded invalidation agree',()=>{const old=seed.value.riffelhornDerived,before=seed.value.riffelhornDependencyState,after=M.change(before,local),a=Object.values(M.assess(after,old)).filter(x=>x.status==='stale').map(x=>x.id).sort();assert.deepEqual(a,M.expectedAffected(before,after,old));assert.equal(a.length,8);assert.ok(a.some(id=>id.endsWith('|area-ratio')));});
test('unaffected regional components reused exactly',()=>{const a=D.resolveGeneration(store,g1).publication.members,b=D.resolveGeneration(store,g2).publication.members,c=D.resolveGeneration(store,g3).publication.members;assert.deepEqual(Object.keys(a).filter(k=>a[k]!==b[k]).sort(),['riffelhornDependencyState','riffelhornDerived']);assert.deepEqual(Object.keys(b).filter(k=>b[k]!==c[k]).sort(),['tryfanDependencyState','tryfanDerived']);});
test('no-op update retains every current result and zero sampling',async()=>{const r=await M.recompute(seed.value.riffelhornDependencyState,seed.value.riffelhornDerived);assert.equal(r.measurement.recomputed,0);assert.equal(r.measurement.sampling,null);assert.deepEqual(r.state,seed.value.riffelhornDerived);});
test('administrative context alone does not stale science',()=>{const c=M.change(seed.value.riffelhornDependencyState,{kind:'admin'});assert.ok(Object.values(M.assess(c,seed.value.riffelhornDerived)).every(x=>x.status==='fresh'));});
test('unknown changed scope is indeterminate and never false absence',async()=>{const ctx=M.change(seed.value.riffelhornDependencyState,{id:'unknown',kind:'unknown',family:'dtm'});assert.ok(Object.values(M.assess(ctx,seed.value.riffelhornDerived)).some(x=>x.status==='indeterminate'));await assert.rejects(M.recompute(ctx,seed.value.riffelhornDerived),/Indeterminate/);});
test('unsupported prospective method stales but cannot execute',async()=>{const ctx=structuredClone(seed.value.riffelhornDependencyState);ctx.expectedMethods.slope='unsupported-prospective-method';assert.equal(Object.values(M.assess(ctx,seed.value.riffelhornDerived)).filter(x=>x.status==='stale').length,176);await assert.rejects(M.recompute(ctx,seed.value.riffelhornDerived),/Unsupported prospective/);});
test('full/scoped parameter revision is numerically and canonically equivalent',async()=>{const ctx=M.change(seed.value.riffelhornDependencyState,{kind:'parameter',probe:'dtm-grid-0-0',stride:2}),a=await M.recompute(ctx,seed.value.riffelhornDerived),b=await M.recompute(ctx,M.empty('riffelhorn'),{full:true});assert.equal(a.measurement.recomputed,2);assert.deepEqual(M.currentContent(a.state),M.currentContent(b.state));});
test('stride-two input scope excludes genuinely unread gap cells',async()=>{const ctx=M.change(seed.value.riffelhornDependencyState,{kind:'parameter',probe:'dtm-grid-0-0',stride:2}),st=(await M.recompute(ctx,seed.value.riffelhornDerived)).state,r=st.results[st.active['dtm-grid-0-0|slope']],u=st.uses[r.inputs[0].ref],bounds=[2624125.6,1091125.1,2624125.8,1091125.4];assert.equal(M.actualIntersection(bounds,u),false);const next=structuredClone(ctx);next.notes.push({key:u.key,bounds,description:'Administrative qualification/use-policy notice gap; no physical observation'});assert.equal(M.assess(next,st)[r.revision].status,'fresh');});
test('missing upstream evidence rejects',()=>{const c=structuredClone(value.tryfanDependencyState);delete c.sources[Object.keys(c.sources)[0]];assert.throws(()=>M.validate(c,value.tryfanDerived),/identity|upstream/);});
test('invalid exact input-use identity rejects',()=>{const st=structuredClone(value.riffelhornDerived);delete st.uses[Object.keys(st.uses)[0]];assert.throws(()=>M.validate(value.riffelhornDependencyState,st),/dependency identity/);});
test('dependency cycle cannot meet immutable identity and finite method topology',()=>{const st=structuredClone(value.riffelhornDerived),id=Object.keys(st.results)[0];st.results[id].inputs=[{kind:'result',ref:id,role:'cycle'}];assert.throws(()=>M.validate(value.riffelhornDependencyState,st),/identity|cycle|Source/);});
test('unsupported cross-source fusion is rejected, not silently reconciled',()=>{const c=structuredClone(value.riffelhornDependencyState);c.tasks.push({id:'dsm-dtm-fusion',kind:'fusion',region:'riffelhorn'});assert.throws(()=>M.validate(c,value.riffelhornDerived),/task\/fusion/);});
test('incompatible unit/reference metadata cannot publish',()=>{const v=structuredClone(value);v.riffelhornDependencyState.sources[Object.keys(v.riffelhornDependencyState.sources).find(k=>k.startsWith('dtm:'))].unitEvidence.bandUnit='unknown';assert.throws(()=>D.prepare(store,v,seed.locators,{ordinal:4,predecessor:g3}),/unit\/support identity/);assert.equal(D.current(store).generation,g3);});
test('method/parameter mismatch cannot validate',()=>{const st=structuredClone(value.riffelhornDerived),id=Object.keys(st.results)[0];st.results[id].parameters.stride=3;assert.throws(()=>M.validate(value.riffelhornDependencyState,st),/identity|parameter/);});
test('stale active output cannot be staged as coherent current state',()=>{const v=structuredClone(seed.value);v.riffelhornDependencyState=M.change(v.riffelhornDependencyState,local);assert.throws(()=>D.prepare(store,v,seed.locators,{ordinal:4,predecessor:g3}),/Stale/);assert.equal(D.current(store).generation,g3);});
test('incomplete recomputation cannot publish',()=>{const v=structuredClone(value);delete v.riffelhornDerived.active['dtm-cluster-0-0|area-ratio'];assert.throws(()=>D.prepare(store,v,seed.locators,{ordinal:4,predecessor:g3}),/Incomplete/);assert.equal(D.current(store).generation,g3);});
test('invalid component membership remains unpublished',async()=>{const s=copied('membership'),g=proposal(s,p=>p.members.riffelhornDerived='0'.repeat(64));await assert.rejects(D.publish(s,g),/unavailable/);assert.equal(D.current(s).generation,g3);});
test('historical stale-but-valid result remains exactly referenceable',async()=>{const p=await D.pin(store,g3),old=seed.value.riffelhornDerived.active['dtm-cluster-0-0|slope'];assert.notEqual(p.result('riffelhorn','dtm-cluster-0-0|slope').result.revision,old);const q=p.result('riffelhorn','dtm-cluster-0-0|slope',old);assert.equal(q.status,'historical');assert.equal(q.assessment.status,'fresh');assert.deepEqual(q.result,seed.value.riffelhornDerived.results[old]);});
test('selected historical/current resolution has no ancestry',async()=>{const s=copied('ancestor');fs.unlinkSync(join(s,'publications',g2+'.json'));for(const g of [g1,g3]){const p=await D.pin(s,g),r=await D.measured(()=>p.result('tryfan','tryfan-summit|slope'));assert.equal(r.value.generation,g);assert.equal(r.measurement.counters.ancestryTraversals,0);assert.equal(r.measurement.counters.membershipVisits,33);assert.equal(r.measurement.counters.componentEdges,11);}});
test('unavailable historical-only derived component fails old pin while current survives',async()=>{const s=copied('historical'),a=D.resolveGeneration(s,g1).publication.members.riffelhornDerived,b=D.resolveGeneration(s,g3).publication.members.riffelhornDerived;assert.notEqual(a,b);fs.unlinkSync(join(s,'components',a+'.json'));await assert.rejects(D.pin(s,g1),/unavailable/);assert.equal((await D.pin(s,g3)).generation,g3);});
test('native evidence qualifications remain exact under extended publications',async()=>{const p=await D.I.pin(store,g3);try{const q=await p.query([{region:'tryfan',query:{place:{crs:'EPSG:27700',point:[266405,359387]},property:'derived-slope'}},{region:'riffelhorn',query:{point:[2624500,1091500],families:['dtm']}}]);assert.ok(q.answers.every(a=>a.generation===g3));assert.equal(q.answers[1].native.results[0].detail.payload.unit.status,'unknown');assert.equal(q.answers[1].native.preparedRevision,D.I.plan.regions.riffelhorn.preparedRevision);}finally{await p.close();}});
function consumer(s,g){const c=spawn(process.execPath,[join(M.H,'worker.mjs'),'consumer',s,g],{stdio:['pipe','pipe','pipe']});let readyResolve,readyReject,queue=[],err='';const ready=new Promise((r,j)=>{readyResolve=r;readyReject=j;});c.stderr.on('data',d=>err+=d);createInterface({input:c.stdout}).on('line',line=>{const a=JSON.parse(line);if(a.ready)readyResolve(a);else{const p=queue.shift();if(a.error)p.reject(Error(a.error));else p.resolve(a.answer);}});c.on('error',readyReject);c.on('exit',code=>{if(code){readyReject(Error(err));for(const p of queue)p.reject(Error(err));}});return {ready,query:q=>new Promise((resolve,reject)=>{queue.push({resolve,reject});c.stdin.write(JSON.stringify(q)+'\n');}),close:()=>c.exitCode!==null?Promise.resolve():new Promise(resolve=>{c.once('exit',resolve);c.stdin.end();})};}
test('isolated consumer pin remains coherent before/during/after derived publication',async()=>{const s=copied('consumer'),old=consumer(s,g1);await old.ready;const q={region:'riffelhorn',question:'dtm-cluster-0-0|area-ratio'};let newer;try{const before=await old.query(q),g=proposal(s,p=>{});assert.deepEqual(await old.query(q),before);await D.publish(s,g);assert.deepEqual(await old.query(q),before);newer=consumer(s,g);assert.equal((await newer.ready).generation,g);const after=await newer.query(q);assert.equal(after.generation,g);assert.notEqual(after.result.revision,before.result.revision);}finally{await old.close();if(newer)await newer.close();}});
test('interrupted derived publication leaves prior root, fresh pin and retry coherent',async()=>{const s=copied('interrupted'),g=proposal(s,p=>{}),r=spawnSync(process.execPath,[join(M.H,'worker.mjs'),'publish',s,g,'before-switch'],{encoding:'utf8',timeout:120000,maxBuffer:4*1024*1024});assert.equal(r.status,91,r.stderr);assert.equal(D.current(s).generation,g3);const view=spawnSync(process.execPath,[join(M.H,'worker.mjs'),'view',s,g],{encoding:'utf8',timeout:30000});assert.equal(view.status,0,view.stderr);assert.equal(JSON.parse(view.stdout).unpublishedRejected,true);D.recover(s);await D.publish(s,g);assert.equal(D.current(s).generation,g);});
